- metadata.json
Required as of c87744aab94a8fae81669dbffb1d44a48a3f3da1 (#509). Only 4.2.0 and up treats integers in strings as being an integer.
Should push a new version to Forge since anyone on less than 4.2.0 will likely be having trouble.
Fixes #537
> metadata: require puppetlabs-stdlib 4.2.0 and up

- manifests/init.pp
This keeps the user from having to duplicate them when defining nginx::config externally.
> Set up relationships for nginx::config even when overridden

- templates/vhost/locations/fastcgi.erb
The hash sorting was started in #532 and this fixes it for fastcgi as well.
/cc @s0enke
> Sort fastcgi params to have stable ordering

- manifests/params.pp
- spec/classes/package_spec.rb
The fact operatingsystemmajrelease does not exists in facter < 1.7 wich is installed by default on debian wheezy. That comes along with puppet 2.7.23 wich should be supported. The resolution is to use lsbmajdistrelease fact.
I only adopted the code for debian, just to here what you think. If you agree, I would also update the code for redhat etc.
> changed $::operatingsystemmajrelease to $::lsbmajdistrelease for Debian

- manifests/resource/vhost.pp
Perhaps there's a subtle gotcha in how Puppet processes conflicting notifications to contained resources.
> closes #541 (maybe: needs user feedback)

- README.markdown
- manifests/init.pp
- manifests/package.pp
- manifests/service.pp
- metadata.json
Give example for passenger in README.md and add OpenBSD to the
supported OSs in metadata.json.
> Allow to use OpenBSD specific service_flags and package_flavors.

- manifests/resource/mailhost.pp
- manifests/resource/vhost.pp
- spec/defines/resource_mailhost_spec.rb
- spec/defines/resource_vhost_spec.rb
- templates/mailhost/mailhost.erb
- templates/mailhost/mailhost_ssl.erb
- templates/vhost/vhost_header.erb
- templates/vhost/vhost_ssl_header.erb
This allows one to pass multiple ipv4/ipv6 addresses to a specific vhost.  I also added ipv6 and a few ssl options to the www redirect block.
> allow listen_ip and ipv6_listen_ip to contain a String or Array

- manifests/config.pp
- spec/classes/config_spec.rb
- templates/conf.d/nginx.conf.erb
Adds functionality and tests for prepending key/value pairs to the top of the nginx configuration. Tests mimicking the http_cfg_append tests have been added since this functionality is identical albeit in a different place. All rspec tests are currently passing. Furthermore, this change is currently working on a CentOS 6.6 (Final) staging box at a client site. I did not add to the README documentation since there doesn't seem to be a good place to put this. Let me know if there is somewhere you want me to add it.
Begin in the manifests/config.pp file with the $nginx_cfg_prepend variable validation. Then check the templates/conf.d/nginx.conf.erb for the added nginx_cfg_prepend block.
By running `bundle exec rake spec` for the unit tests. Tests have been added for this change.
At Railsdog …
> Prepend to the nginx config block

- manifests/package/debian.pp
- spec/classes/package_spec.rb
Since commit 531ef9 of puppetlabs-apt, the gpg key (apt::key) is
checked, and should use the long format.
This value is validated with a regex enforcing it to only contain valid
hexadecimal characters, be precisely 8 or 16 hexadecimal characters long
and optionally prefixed with 0x for key IDs, or 40 hexadecimal
characters long for key fingerprints.
https://github.com/puppetlabs/puppetlabs-apt/commit/f588f2651a68c5863aac7dac910d96bbc7531ef9
This patch fixes the puppet warning below:
```puppet
Warning: /Apt_key[Add key: 7BD9BF62 from Apt::Source nginx]: The id should be a full fingerprint (40 characters), see README.
```
> apt::key: puppetlabs-apt check now the full GPG fingerprints.

- manifests/package/debian.pp
- spec/classes/package_spec.rb
The new puppetlabs/apt module requires 40 character apt keys or it will spit out warnings. Can you merge this bad boy to master so I can remove the warning?
Thanks,
Erik
> Changing apt key to 40 characters to support new apt module

- manifests/service.pp
Flags parameter is only supported on OpenBSD and breaks on some other systems like RH (on puppet 3.4.x)
See the discussion here: https://github.com/jfryman/puppet-nginx/commit/2960c10cd
> Flags parameter supported only on OpenBSD

- manifests/package.pp
This broke some SLES compatibility.
> Fix possibility to set package name

- .travis.yml
- Gemfile
- spec/classes/config_spec.rb
- spec/defines/resource_geo_spec.rb
- spec/defines/resource_location_spec.rb
- spec/defines/resource_mailhost_spec.rb
- spec/defines/resource_map_spec.rb
- spec/defines/resource_upstream_spec.rb
- spec/defines/resource_vhost_spec.rb
Move to rspec-puppet 2. Allows future parser testing on the latest 3.x version, where before it only worked up to 3.5.x
> Rspec puppet 2

- .travis.yml
- Gemfile
- spec/classes/config_spec.rb
- spec/defines/resource_geo_spec.rb
- spec/defines/resource_location_spec.rb
- spec/defines/resource_mailhost_spec.rb
- spec/defines/resource_map_spec.rb
- spec/defines/resource_upstream_spec.rb
- spec/defines/resource_vhost_spec.rb
Puppet 4 is on the horizon so we don't want to introduce code that's known to be incompatible with it.
Merge #587 before this.
> Don't allow failures when using the future parser

- manifests/package/redhat.pp
When $package_name is not 'nginx' the dependency on the package resource would be incorrect.
Probably never an issue in practice since 'nginx' is the package name in the nginx.org repo, but addresses my OCD
> package/redhat: correct dependency on package

- .gitattributes
The Github file type detection is not foolproof, and .pp file extension is shared by Pascal.
Sometimes our files are detected as Pascal, not Puppet as they should be.
This change ensures all *.pp files are recognized as Puppet files.
See https://github.com/github/linguist/issues/2318
> gitattributes: add file so all *.pp is recognized as Puppet on Github

- metadata.json
Also:
* Remove "description" field (is deprecated)
* Declare support for Debian 7
* Remove the ".0" part of the version number for Debian & Red Hat
> metadata: add Puppet version compatibility

- spec/defines/resource_location_spec.rb
- templates/vhost/location_header.erb
- templates/vhost/locations/directory.erb
- templates/vhost/locations/proxy.erb
Allows setting these directives on any location:
* auth_basic
* auth_basic_user_file
Fixes #600 
Fixes #260
> location: move auth_basic directives to header

- manifests/resource/vhost.pp
The comments indicate that `index_files` set on the vhost is used for the default location, but it doesn't currently do that. This pull fixes that.
> Fixing default location to use specified index files.

- manifests/resource/location.pp
- spec/defines/resource_location_spec.rb
All it's doing right now is copying a file, but the copy of the file is never referenced by the template.
Fixes #572
> location: remove the auth_basic_user_file resource

- manifests/package/debian.pp
- metadata.json
- spec/classes/package_spec.rb
puppetlabs-apt 2.0.0 drops support in apt::source for key_source and required_packages.
* key_source will default to keyserver.ubuntu.com which carries both keys, so it
doesn't need to be explicitly defined
* required_packages can be emulated with the package resource
Fixes #611
> package/debian: support puppetlabs-apt 2.0.0

- manifests/resource/vhost.pp
- spec/defines/resource_vhost_spec.rb
- templates/vhost/vhost_header.erb
- templates/vhost/vhost_ssl_header.erb
Passenger 5.0 deprecates passenger_set_cgi_param and replaced it with passenger_set_header and passenger_env_var. This allows you to specify those parameters.
https://blog.phusion.nl/2015/03/04/phusion-passenger-5-0-1-released/
> Add passenger_set_header and passenger_env_var parameters for Passenger 5.0+

- .travis.yml
- Gemfile
- manifests/resource/location.pp
No need to test with future parser, the real thing is here.
> travis: test on Puppet 4 for real

- manifests/params.pp
Install from upstream by default like for other OSs
Fixes #620
> Add support for Debian 8

- manifests/resource/location.pp
- manifests/resource/mailhost.pp
- manifests/resource/vhost.pp
In the last puppetlabs-concat version the ensure parameter was deprecated inside the concat::fragment
I've removed all the matches i've found and run the tests successfully.
Hope it can be merged.
Regards
M
> remove ensure from concat::fragment as its deprecated

- templates/vhost/vhost_ssl_header.erb
- templates/vhost/vhost_ssl_settings.erb
fixes jfryman/puppet-nginx#542
> Include ssl settings in rewrite_www server.

- Rakefile
- manifests/package/debian.pp
The lint rake task had stopped failing on warnings for some reason... this PR re-enables it.
> Fail on lint warnings

- .travis.yml
The Ruby 1.8.7 tests have been broken for ages, and it's unlikely anyone will do the work to restore support for the tests. Drop them from the suite to save Travis CI from doing work for nothing on every commit.
> travis: drop ruby 1.8.7 tests

- manifests/resource/upstream.pp
- manifests/resource/vhost.pp
Hello James
Not sure if this issue is related to the changes in the concat module, but since it was updated we start having errors like:
==> single: Error: Could not set 'file' on ensure: No such file or directory - /etc/nginx/conf.d/drupal-upstream.conf20150506-4095-ep3q6b.lock
==> single: Error: Could not set 'file' on ensure: No such file or directory - /etc/nginx/conf.d/drupal-upstream.conf20150506-4095-ep3q6b.lock
==> single: Wrapped exception:
==> single: No such file or directory - /etc/nginx/conf.d/drupal-upstream.conf20150506-4095-ep3q6b.lock
==> single: Error: /Stage[main]/Dotdrupal/Dotdrupal::Site[drupal]/Dotdrupal::Nginx[nginx for drupal]/Nginx::Resource::Upstream[drupal]/Concat[/etc/nginx/conf.d/drupal-upstream.conf]/File[/etc/nginx/conf.d/drupal-upstream.conf]/ensure: change …
> Require base folder for resources

- manifests/config.pp
- spec/classes/config_spec.rb
I've added loose management and creation of the nginx access log and error log files. If they don't exist then nginx will not pass its config test and won't start up (on FreeBSD at least), so these files need to exist prior to nginx being started or reloaded.
I've included specs which are passing, and I think testing the right things I'm not very familiar with testing puppet yet. Testing my branch on a virtual machine results in a successfully started nginx service too.
I also think I've managed to stick to the style guidelines, I've run the `rake lint`, `rake syntax` and `rake validate` tasks and I think they've all passed as well.
I'm not sure if this is the right thing to do or not though
``` puppet
if $vhost_purge == true {
File[$log_dir] {
purge   => true,
recurse => true,
}
}
``` …
> Create directory for log files

- manifests/resource/upstream.pp
- manifests/resource/vhost.pp
Reverts #624
The puppetlabs-concat 2.x series has been yanked from release. These changes are no longer necessary.
More at https://groups.google.com/forum/#!topic/puppet-users/4_Sxrfl4uUY
> Revert "Require base folder for resources"

- manifests/resource/vhost.pp
I don't think this is such an improvement (over non qualification).
My main motivation comes from the fact that it is not currently supported so well by "language-puppet".
> Don't qualified call to defined resource type

- docs/hiera.md
As described in issue #536, the example on how to use nginx correctly without hiera needs to be updated to fix parse-order dependency with defined(nginx::config) with puppet 3.x.
> Update non-hiera usage (see #536)

- manifests/resource/upstream/member.pp
- templates/vhost/location_footer.erb
I'm using stored configs to create upstream::member on servers that should belong to up upstream.  Removing them while developing the puppet manifests if something goes wrong is troublesome without the ability to ensure => absent.
All tests are passing under ruby 2.1.2, though I didn't add new ones.
> Add 'ensure' parameter to resource::upstream::member.

- manifests/resource/upstream.pp
- templates/conf.d/upstream_member.erb
- templates/conf.d/upstream_members.erb
As defined in nginx upstream documentation: http://nginx.org/en/docs/http/ngx_http_upstream_module.html#upstream
I added this optional parameter because we folks have to deal with a finicky backend that randomly timeout on a single request  when under heavy load. When this happens, the upstream gets disabled for 10 seconds (fail_timeout) and for that period of time other upstreams receive the requests which doesn't play nice with our application. 
Increasing this parameter to max_fails=3 ensures that load is switched only when really necessary. 
```
nginx::resource::upstream { $upstream_name:
ensure               => present,
members              => $upstream_servers,
upstream_cfg_prepend => {
'ip_hash'   => '',
'keepalive' => '128',
},
upstream_max_fails   => 3,
}
```
becomes s: 
``` …
```
> adding a max_fails parameter to upstream member[s]

- spec/defines/resource_vhost_spec.rb
- templates/vhost/vhost_header.erb
- templates/vhost/vhost_ssl_header.erb
Was not working when server_name was an array
with
```
server_name            => [ 'a.example.com', 'b.example.org' ],
rewrite_www_to_non_www => true,
```
Before patch:
```
server {
[...]
server_name www.a.example.com;
return 301 http://a.example.com$request_uri; 
}
[...]
server {
[...]
servername a.example.com
[...]
}
```
now:
```
server {
[...]
server_name www.a.example.com;
return 301 http://a.example.com$request_uri; 
}
server {
[...]
server_name www.b.example.org;
return 301 http://b.example.org$request_uri; 
}
[...]
server {
[...]
servername a.example.com b.example.org
[...]
}
```
```
> iterate server_name when rewrite_www_to_non_www is used

- manifests/resource/location.pp
Comparison was causing an error with parser = future and stringify_facts = false. This ensures that the comparison is done between two integers
Fixes: #684
> Convert $priority to integer before comparison

- README.markdown
- docs/quickstart.md
I've written a bit of documentation regarding the NGINX Puppet module - mostly a 'quick start' guide or people who are either new to this module, or new to NGINX itself.  I have a couple of motivations for adding to the documentation:
1.  I have used this module *a lot* - it's been very helpful in managing the infrastructure I manage day-to-day.  I am, of course, grateful for the work the contributors have put in to the module and I also want to encourage use (and reuse) as I've seen people jump into creating hard-to-reuse manifests because they didn't understand this module or how to use it.  (Mostly by beginners.)
2.  I've written instructions similar to this a number of times - rather than continue that work, I'd like to contribute this quick guide to the project itself.
I hope you …
> Adding a QuickStart Guide to the NGINX Module

- manifests/config.pp
- manifests/resource/streamhost.pp
- manifests/resource/upstream.pp
- spec/defines/resource_stream_spec.rb
- templates/conf.d/nginx.conf.erb
- templates/streamhost/streamhost.erb
Adding support for stream configuration within NGINX.  Most of the code is copied from existing classes with parameters adjusted accordingly.  Mainly added a flag to the upstream configuration of http|stream so upstreams can be targeted to the appropriate context with http being the default value for backwards compatibility.
> Adding support for stream configuration

- manifests/config.pp
- spec/classes/config_spec.rb
- templates/conf.d/nginx.conf.erb
This patch allows to set the severity level for error_log.
If not set it will use the default severity level of 'error'.
$nginx_error_log_severity is validated to only allow valid values.
> Add parameter to allow setting error_log severity level

- manifests/resource/vhost.pp
- spec/defines/resource_vhost_spec.rb
- templates/vhost/vhost_header.erb
nginx can listen on unix sockets in addition to v4 and v6 addrs. This adds parameters to permit this use case.
http://nginx.org/en/docs/http/ngx_http_core_module.html#listen
The parameters emulate the ipv6 implementation. The enable parameter only affects listen in the unix socket case (not things like proxy_pass), so I called this listen_unix_socket_enable rather than unix_socket_enable.
> Add unix socket for listening.

- manifests/init.pp
It may be better to reload instead of restart to prevent broken connections on production environment.
From official nginx doc:
Once the master process receives the signal to reload configuration, it checks the syntax validity of the new configuration file and tries to apply the configuration provided in it. If this is a success, the master process starts new worker processes and sends messages to old worker processes, requesting them to shut down. Otherwise, the master process rolls back the changes and continues to work with the old configuration. Old worker processes, receiving a command to shut down, stop accepting new connections and continue to service current requests until all such requests are serviced. After that, the old worker processes exit.
> Replaced restart by reload

- manifests/resource/vhost.pp
`nginx::resource::location` defaults this value to
`$::nginx::config::proxy_set_headers`, whereas `nginx::resource::vhost`
defaults it to `[]`. This means that you get a different set of defaults
if you use an explicit `nginx::resource::location` resource as opposed to
setting it up via an `nginx::resource::vhost` with a proxy attribute.
Updating this default value to be consistent will be less surprising.
> Update vhost proxy_set_header defaults to match location

- manifests/resource/location.pp
This is PR #676 reborn.   Ensure isn't currently respected on location resources, so they don't get deleted from stored configs.
> Ensure isn't being respected on locations.

- manifests/config.pp
- manifests/resource/location.pp
- manifests/resource/vhost.pp
- metadata.json
- spec/defines/resource_location_spec.rb
- templates/conf.d/nginx.conf.erb
- templates/vhost/locations/proxy.erb
Adding ability to specify multiple proxy_cache_path entries with unique proxy_cache_keys_zone values
> Multiple proxy_cache_path entries

- manifests/resource/location.pp
- spec/defines/resource_location_spec.rb
This change orders locations the same way if a virtual host supports both http and https. Also if two virtual hosts have the same locations the ordering is identical.
> improved location ordering

- spec/classes/service_spec.rb
@jfryman related with pull request 702 comment from me. review ad confirm please.
https://github.com/jfryman/puppet-nginx/pull/702
> restart replaced with reload in service_spec.rb file

- manifests/resource/vhost.pp
Hi,
I add the paramter locations. With this, you can write more cleaner hiera.
Also, puppetlabs/apache has this option, too.
An exmaple based from the example on the README:
```
nginx::nginx_vhosts:
'www.puppetlabs.com':
www_root: '/var/www/www.puppetlabs.com'
locations:
'static':
location: '~ "^/static/[0-9a-fA-F]{8}\/(.*)$"'
'userContent':
location: /userContent
'rack.puppetlabs.com':
proxy: 'http://puppet_rack_app'
```
> Added locations paramater to use it in hiera.

- .travis.yml
From https://docs.travis-ci.com/user/caching:
> On Ruby and Objective-C projects, installing dependencies via Bundler can make up a large portion of the build duration. Caching the bundle between builds drastically reduces the time a build takes to run.
> travis: enable bundler caching in builds

- manifests/resource/location.pp
- manifests/resource/upstream/member.pp
>Warning: Scope(Concat::Fragment[fqdn-500-6666cd76f96956469e7be39d750cc7d9]): The $ensure parameter to concat::fragment is deprecated and has no effect.
Resolves this error when using puppetlabs-concat 2.x
Closes #759
> Supress warnings with concat 2.x

- manifests/config.pp
- templates/conf.d/nginx.conf.erb
The current default value is not ideal, as 'text/html' is always included whether specified in the config or not. If it's specified, nginx shows a warning on start up.
Fixes #748
> Allow removal of gzip_types from the config

- manifests/resource/mailhost.pp
- manifests/resource/streamhost.pp
- manifests/resource/upstream/member.pp
- manifests/resource/vhost.pp
- spec/defines/resource_mailhost_spec.rb
- spec/defines/resource_vhost_spec.rb
with puppet 4 the following is no longer true: 1 == '1'. So with puppet 4 it
must be ensured, that when variables are compared either both are integer or
both are strings.
> bugfix: convert integer strings to integer

- manifests/config.pp
- spec/classes/config_spec.rb
- templates/conf.d/nginx.conf.erb
Adding the option to manage accept mutex and accept mutex delay. Defaults taken from here: http://nginx.org/en/docs/ngx_core_module.html#accept_mutex.
> Add events accept mutex delay

- manifests/resource/location.pp
- manifests/resource/vhost.pp
- spec/defines/resource_location_spec.rb
- templates/vhost/locations/proxy.erb
Nginx supports multiple proxy_cache_valid directives.
This allows to specify a different caching time for different response codes.
(http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_valid)
This PR adds the possibility to specify an array of strings for the 'proxy_cache_valid' attribute, while preserving backwards compatibility by still accepting a string (which is the expected behavior today). 
Also, a unit test has been added that covers the new behavior, hence both the current and the new behavior is tested.
> Add support for multiple 'proxy_cache_valid' directives

- templates/vhost/vhost_header.erb
- templates/vhost/vhost_ssl_header.erb
> Resolving issue #803 by adding quotes around the parameters

- docs/quickstart.md
The link for NGINX Documentation had a typo and wasn't rendering correctly.  I also corrected lowercase "puppet" to uppercase "Puppet" where the documentation was describing the project, "Puppet," and not the command, "puppet."
> Corrected quickstart documentation

- manifests/resource/vhost.pp
- templates/vhost/vhost_ssl_settings.erb
Support for http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_session_tickets
> Add ssl_session_tickets and ssl_session_ticket_key parameters

- manifests/init.pp
- manifests/service.pp
- spec/classes/service_spec.rb
Puppet managing the service is not desirable in every environment.
Use `?w=1` to omit whitespace changes.
> Add manage_service parameter

- manifests/config.pp
- manifests/init.pp
- manifests/resource/location.pp
- manifests/resource/vhost.pp
- spec/classes/config_spec.rb
- spec/defines/resource_location_spec.rb
- templates/conf.d/nginx.conf.erb
- templates/vhost/locations/proxy.erb
I need this to hide X-Frame-Options for a single location block.
From nginx docs about proxy_hide_header:
By default, nginx does not pass the header fields “Date”, “Server”,
“X-Pad”, and “X-Accel-...” from the response of a proxied server to a
client. The proxy_hide_header directive sets additional fields that will
not be passed.
> Support for proxy_hide_header directive.

- lib/facter/nginx_version.rb
If this fact is not confined it will display a dialog on Windows which requires interaction.  If puppet runs silently, it will hang.
Fixes #814
> Confine nginx_version fact

- .travis.yml
* Test Puppet 3.0 on Ruby 1.9.3, everything else on latest Ruby 2.1.10
* Test Puppet 3.0 on future parser again
* Test with strict variables, but don't fail the build if it fails (yet!)
> travis: enhance the configuration

- lib/facter/nginx_version.rb
CentOS 7 (default fact works): nginx version: nginx/1.10.0
CentOS 6: nginx: nginx version: nginx/1.0.0
Fixes #799
> make fact work on old nginx as well

- Gemfile
- metadata.json
claim support for puppet 4, AIX, FreeBSD & NetBSD
add enable metadata-json-lint gem so syntax is checked in future
> Enhance module metadata

- manifests/resource/upstream.pp
- manifests/resource/upstream/collect.pp
This is an attempt to fix issue #720 .  I can only do minimal testing as I don't have a master environment to test with.  I believe this should fix the issue and retain functionality, based on other modules that have addressed the same problem.
Fixes #720
> Remove storeconfigs warning on puppet apply

- manifests/config.pp
- spec/defines/resource_location_spec.rb
- templates/vhost/fastcgi_params.erb
Should possibly go together with https://github.com/jfryman/puppet-nginx/compare/httpoxy-test
If you guys are already working on a httpoxy fix, just reject this pull request. 
Thanks.
> Mitigating Httpoxy 

- Gemfile
json_pure 2.0.2 requires ruby 2.0 or higher
> gemfile: pin json_pure to 2.0.1 or lower on ruby 1.x

- manifests/config.pp
- manifests/init.pp
- templates/conf.d/nginx.conf.erb
see http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_path
> Add use_temp_path into proxy_cache_path

- manifests/package/debian.pp
We faced the problem that when using the puppet-nginx module and managing ca-certificates on our own it will bring up problems only because of assigning the same resource twice.
(ensure_resources() would be nice to use but I didn't want to add additional dependencies)
> Conditionally adding the packages if they are not added previously

- manifests/resource/location.pp
- manifests/resource/vhost.pp
- spec/defines/resource_location_spec.rb
- templates/vhost/locations/proxy.erb
This allows us to configure nginx' [proxy_buffering](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering).
More specifically, it allows us to disable it, for the rare occasions
when this is needed.
Closes #840 
Closes #853
> add proxy_buffering parameter to location & vhost

- Gemfile
Reverts jfryman/puppet-nginx#857
This is no longer necessary - it was added to work around a problem with puppetlabs_spec_helper 1.2.0. However that release was yanked, so this is no longer required.
> Revert "pin rubocop and rubocop-rspec depending on Ruby version"

- manifests/config.pp
- manifests/init.pp
- spec/classes/config_spec.rb
- templates/conf.d/nginx.conf.erb
set it to default value of 100 as shown in nginx config
Require this parameter as default value results in a huge number of TIME_WAIT connections with high QPS applications hitting nginx
The check has been copied from the keepalive_timeout parameter
> [keepalive_requests] added keepalive_requests parameter in nginx.conf

- manifests/resource/location.pp
- templates/vhost/locations/try_files.erb
This is already possible through location_custom_cfg with a manifest
that looks like:
nginx::resource::location { 'location name':
location  => '/',
vhost     => 'any vhost',
location_custom_cfg => {
'try_files' => '$uri $uri/ @rewrite',
}
}
This change simplifies the part by allowing to use the try_files
directive on its own (without only in combination with, e.g., www_root):
nginx::resource::location { 'location name':
location  => '/',
vhost     => 'any vhost',
try_files' => [ '$uri', '$uri/', '@rewrite' ],
}
That looks a bit better as know the user doesn't need to think about,
if he can use try_files or need to use location_custom_cfg in the current
context, anymore.
fixes #470
> Allow locations with try_files only

- spec/spec_helper_acceptance.rb
(re #882): Still getting a failure, but putting in this PR for when we get acceptance tests working with newer Beaker version. Presumably we should also require a specific version more explicitly?
> Fix acceptance test failures with newer Beaker versions

- README.md
- docs/quickstart.md
- manifests/package/redhat.pp
- spec/acceptance/class_spec.rb
- spec/classes/package_spec.rb
- spec/spec_helper_acceptance.rb
This contains elements of @jlambert121's #786, but addresses @3flex's feedback from back in June, as well as improving test coverage slightly. It's also based against current upstream, so shouldn't need a rebase.
If preferred, I can submit on top of #786, but wasn't sure how to do that.
> add support for passenger on CentOS/RHEL

- manifests/resource/vhost.pp
- spec/defines/resource_vhost_spec.rb
- templates/vhost/vhost_footer.erb
passenger_pre_start (unlike other passenger settings that are not directly in the module, and can be easily added with an 'append' directive inside the vhost) has to be outside the scope of the `server {}` block. If this is too specific, I could alternatively make a different append variable that appends in the vhost file but outside that block.
I believe it might be possible to put it in `http {}` also, but most examples show it following the `server {}` block, but outside of its scope. 
https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_pre_start
Since the required stdlib version still doesn't seem to have a validate_url function, I just validated that it was a string, rather than trying to come up with a regex that would validate all possible valid URLs.
I added …
> add $passenger_pre_start variable

- .sync.yml
- spec/acceptance/nginx_mail_spec.rb
- spec/acceptance/nginx_vhost_spec.rb
- spec/spec_helper_acceptance.rb
Depends on https://github.com/voxpupuli/modulesync_config/pull/230
It's safe to merge without that change and a new module sync, but the changes in `.sync.yml` would be redundant.
> Configure acceptance tests on docker on travis

- docs/quickstart.md
- spec/acceptance/nginx_vhost_spec.rb
- spec/spec_helper_acceptance.rb
@3flex @ffrank 
Here's one more related to the now-merged #876 
@3flex says that #885 should address the other test failure (though there will probably be a conflict if one isn't rebased after the other is merged).
I also added the `--fail` (`-f`) option to curl for the vhost test calls that rely on exit status, which should return a non-zero exit code if there's a non-2XX response. Normally, curl will exit non-zero if there's a failure to connect in the first place, but if it connects and gets a 4XX or 5XX response, it will display the error but exit 0.
```
[root@centos-7-x64 tmp]# curl localhost
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.1</center>
</body>
</html>
[root@centos-7-x64 tmp]# …
```
> more test and docs fixes for acceptance tests for CentOS / Passenger

- templates/conf.d/nginx.conf.erb
- templates/vhost/vhost_header.erb
- templates/vhost/vhost_ssl_footer.erb
- templates/vhost/vhost_ssl_header.erb
I think this should make at least some improvement w/r/t #742, would love to see some folks test this in the wild, but at the least, should only affect spacing.
Based on the example configs in the acceptance tests, at least, the spacing looks Ok to me.
```
root@ubuntu-server-1404-x64:/etc/nginx/sites-available# cat www.puppetlabs.com.conf 
server {
listen *:80;
server_name           www.puppetlabs.com;
index  index.html index.htm index.php;
access_log            /var/log/nginx/www.puppetlabs.com.access.log combined;
error_log             /var/log/nginx/www.puppetlabs.com.error.log;
location / {
root      /var/www/www.puppetlabs.com;
index     index.html index.htm index.php;
}
}
server {
listen       *:443 ssl;
server_name  www.puppetlabs.com;
ssl on;
ssl_certificate …
```
> try to improve spacing in generated configs (Issue #742)

- manifests/config.pp
- manifests/resource/vhost.pp
- spec/classes/config_spec.rb
- spec/defines/resource_vhost_spec.rb
- templates/conf.d/nginx.conf.erb
- templates/vhost/vhost_header.erb
- templates/vhost/vhost_ssl_header.erb
This PR should preserve backwards compatibility, but allows to specify multiple access and error log directives by passing in an array, resulting in something like the following:
```
access_log            /var/log/nginx/test.log combined;
access_log            syslog:server=localhost combined;
error_log             /var/log/nginx/test-error.log;
error_log             syslog:server=localhost;
```
This allows more complex configurations, admittedly at the cost of doing more work in the template, something that it seems was intentionally avoided before. Note that the severity (for main error log) or access log format (in http or vhost scope) can't be set separately per logfile, though I think this could still be done if necessary using raw config appends (or I could change it to take a hash …
> Allow multiple access / error logs in main config and vhosts, other logging changes

- manifests/config.pp
- spec/classes/config_spec.rb
This is an update of #812, which seems reasonable to me, though would appreciate another look.
I just did an extra commit which removes the tests for some of the removed items.
> update of #812 (No reasons to manage separate files since confd_purge is available)

- manifests/resource/mailhost.pp
- spec/defines/resource_mailhost_spec.rb
- templates/mailhost/mailhost.erb
- templates/mailhost/mailhost_ssl.erb
Add the ability to specify auth_http_header in mailhost
> add auth_http_header

- lib/facter/nginx_version.rb
Update of #890 that should apply to current master and preserve original authorship of commit.
@shoikan @alexjfisher 
(I tried making a pull request against the pull request, but because that master is now out of date again, it didn't work).
> Prevent custom fact from complaining when openresty is installed

- manifests/notice/config.pp
This should address one of the comments in #905 
As far as whether we should still have that warning, given that #501 said we're no longer forcing puppet-module-data pattern, I'll leave that up to others, but this one seems safe to merge.
> update URL in notice

- manifests/config.pp
- manifests/init.pp
- spec/classes/config_spec.rb
- spec/classes/nginx_spec.rb
This creates the missing streams-available and streams-enabled
directories if stream is true and allow the streamhost resources
to be created from hiera.
Some simple tests are included.
This commit might replace PRs:
- Fix streams support #790
- Fixing Streamhost implementation support #784
> Add missing stream dirs and create streams from hiera

- manifests/resource/vhost.pp
I think this might help with #894.
It passes spec and acceptance tests, but would like a review of this to make sure it's sane and makes sense. I couldn't think of an easy way to test this, but let me know if there's a test I should add.
> 'Require' vhost dir / enable dir in files

- spec/spec_helper.rb
- spec/unit/facter/util/fact_nginx_version_spec.rb
One way of solving #917: don't use mocha at all
> Changes mock from mocha to rspec-mock

- manifests/config.pp
- manifests/init.pp
- manifests/resource/location.pp
- manifests/resource/vhost.pp
- spec/classes/config_spec.rb
- spec/defines/resource_location_spec.rb
- templates/conf.d/nginx.conf.erb
- templates/vhost/locations/proxy.erb
It is better to explicitly define this than using raw_append or raw_prepend.
From nginx docs:
Permits passing otherwise disabled header fields from a proxied server to a client.
By default, nginx does not pass the header fields "Date", "Server", "X-Pad", and "X-Accel-..." from the response of a proxied server to a client.
> Support for proxy_pass_header directive.

- metadata.json
Just what the title says. While it may still work, we should take official support for RHEL 5, Debian 5-6, Ubuntu 10.04 in the metadata, and add support for Debian 8 (which I believe is supported).
As to whether we will continue to list Solaris, AIX, NetBSD, etc. in the metadata, I haven't changed any of that.
> Deprecate (RHEL 5, Debian 5-6, Ubuntu 10.04) in module metadata

- manifests/init.pp
- manifests/service.pp
- spec/classes/service_spec.rb
Per #916, the `$configtest_enable` option doesn't seem if it could possibly work. In general, it would be good to review if everything here does what it is supposed to, but I think this will do the right thing on most platforms without any additional work.
I'm not sure if anyone would be using the `$service_restart` command directly, I'd think in most cases, we should be relying on `$service_name` and letting Puppet do the right thing, though I'm open to suggestion if people think `$service_restart` still needs to be exposed directly. What I don't understand is that, though it defaults to `/etc/init.d/nginx reload`, which doesn't work, the systems I tested all were using systemctl to restart the service anyway.
We still may want to revisit some kind of reporting back if the config test …
> Remove broken configtest_enable option

- manifests/resource/location.pp
- spec/defines/resource_location_spec.rb
Rework #414 (h/t to @zshahan)
Instead of switching it to use `$title`, I did `$vhost:$title`, which I *think* will work better given the different possible cases (default location, non-default location, etc.). Let me know if my thinking is off there, but I think except for default-foo, $title won't contain the vhost name?
> add debugging information in error message 

- manifests/resource/location.pp
- spec/defines/resource_location_spec.rb
- templates/vhost/location_header.erb
This is an update of #746, since @snowmean didn't have time to resolve conflict / add tests.
> Add expires directive to location

- manifests/resource/location.pp
- spec/defines/resource_location_spec.rb
- templates/vhost/locations/uwsgi.erb
This patch allows custom uwsgi params to be added with uwsgi_param, same way fastcgi_param work.
@wyardley, It is a replacement for #767
> uwsgi: allow custom uwsgi_param directives

- manifests/resource/location.pp
- spec/defines/resource_location_spec.rb
See #741 
I did not add any additional tests here, if anyone has a suggestion of a test that should be added, I can add one.
This also simplifies the syntax a little, will need to verify that the changes work as I expect with all Puppet versions.
> Allow location_allow / location_deny as well in location blocks

- manifests/config.pp
- manifests/init.pp
- manifests/resource/location.pp
- manifests/resource/streamhost.pp
- manifests/resource/vhost.pp
- spec/classes/config_spec.rb
- spec/defines/resource_stream_spec.rb
- spec/defines/resource_vhost_spec.rb
- templates/conf.d/nginx.conf.erb
This PR adds an option `$confd_only` (defaulting to false), that avoids using the Ubuntu style `$conf_dir/sites-{available,enabled}` mechanism with symlinks. Obviously, the current way works, but I don't personally prefer it; also, presumably one is using Puppet to manage configs in a lot of scenarios, so on platforms where this convention isn't used, or when managing all of the nginx configs through Puppet, the symlinks don't really gain you much advantage.
A couple notes:
1) It just doesn't force the resource if the param is set, so `$conf_dir/sites-{available,enabled}` won't be forced to be present or absent
2) To purge, with `$confd_only` set, both `$vhost_purge` and `$confd_purge` must be set, otherwise, it will silently not purge (I can make it fail in that case if folks think it's …
> Add confd_only option

- manifests/resource/map.pp
- spec/defines/resource_map_spec.rb
- templates/conf.d/map.erb
This is a rebase of #698, also updated to follow Rubocop's enforced conventions. It passes tests, but I don't use this feature, and haven't done any work to verify that it works as expected.
Given that the module doesn't support Ruby 1.8.7 anymore, it might also be possible to fix this in a different way (just going off @btisdall's comment).
> Allow mappings to be supplied as array of hashes.

- manifests/config.pp
- manifests/init.pp
- manifests/resource/streamhost.pp
- spec/defines/resource_stream_spec.rb
- templates/conf.d/nginx.conf.erb
- templates/streamhost/streamhost.erb
h/t to @modax and @alwiesner)
This is my attempt to combine #790, #784, while also incorporating the changes from #878. It adds back the $stream variable, which I incorrectly removed in #878, thinking it wasn't used in the nginx.conf tepmlate (it is). The placement of the various conditionals could be reworked if folks think it would be easier to read or less confusing. Would love suggestions as far as any tests that should be added.
This should address #s 1,2,3 from #784, but in a way that applies cleanly to current master and doesn't include any extraneous commits.
It looks like `$stream` did, in fact, control including `/etc/nginx/conf.stream.d`, however, maybe that include didn't get updated when someone added support for `streams-{enabled,available}`. The configs will still get built …
> Fix streamhost support

- manifests/config.pp
- manifests/init.pp
- spec/classes/config_spec.rb
- templates/conf.d/nginx.conf.erb
Noticed this in @garethr's talk -- currently, there's no way without using a custom config to turn `$daemon` off. Obviously, this is something that probably wasn't useful to most people before, but becomes a lot more useful if used along with containerization.
This doesn't change the existing behavior, but allows it to be explicitly set to 'on' or 'off' via a parameter (this is still just the string on / off; #457 addresses possibly allowing booleans to work instead or in addition to).
Let me know if these tests look reasonable.
> Allow setting $daemon to "on" or "off" (defaults to unset)

- manifests/params.pp
- metadata.json
Per #935, seems to work on 16.04 (though need to get acceptance tests working, see https://tickets.puppetlabs.com/browse/BKR-970). We should update metadata and add 'xenial' to the array in params (any reason not to use the release # here?)
> officially add Ubuntu 1604 support

- manifests/config.pp
- spec/defines/resource_location_spec.rb
- templates/vhost/locations/proxy.erb
I think this is pretty simple and sane, though does change the default 'location' config when proxy is enabled.
cc:  @keymone
> default proxy_redirect to undef in locations (resolves #395)

- manifests/resource/vhost.pp
- spec/defines/resource_vhost_spec.rb
Without this change, specifying fastcgi parameters are not possible on
the vhost.  This change modifies vhost resource to allow passing the
fastcgi_param to the location resource directly, as is the case with a
few of the other fastcgi related parameters.
> Add fastcgi_param parameter to vhost resource

- manifests/config.pp
- manifests/params.pp
- spec/classes/config_spec.rb
Does this look sane as a fix for #664? This is one we should definitely try and get right, as it could cause problems if the ownership isn't correct on various platforms.
1. Should this also have an interface in `::nginx` as well as `::nginx::config`? I think with new parameters, it's better not to do that until we work out the exact structural changes.
1. @bastelfreak: can you confirm permissions on ArchLinux?
I added `log_mode` in nginx::config, as I think it's important to have a sane default that's restrictive (0700), but people often do also need to grant group / other permissions on the nginx logdir that are custom. We could make the default 0750 or 0751 if that makes more sense.
> Set log directory ownership / permissions explicitly

- templates/conf.d/map.erb
Currently our team still requires support for RHEL and CentOS6.7 releases. This has a back level 
ruby of 1.8.7 the  map.erb doesn't compile correctly
erb -x -T '-' map.erb | ruby -c
-:17: syntax error, unexpected '|', expecting tCOLON2 or '[' or '.'
... @mappings.inject(0) { |l,(h)| h['key'].size > l ? h['key']....
^
-:17: syntax error, unexpected '}', expecting kEND
...size > l ? h['key'].size : l } 
With the latest changes to  Ran UT test. This is the relevant section and the final tally
nginx::resource::map
os-independent items
basic assumptions
should contain File[/etc/nginx/conf.d/backend_pool-map.conf] with owner => "root", group => "root", mode => "0644", ensure => "file" and content =~ /map \$uri \$backend_pool/
map.conf template content
when hostnames is true
should contain …
> fix map.erb to work on Redhat 6 releases

- manifests/resource/location.pp
- spec/defines/resource_location_spec.rb
- Fixes: ensure => absent was not working on nginx::resource::location
- Added tests to avoid happening again
I hope this helps. We are having this issue since we updated the module version. Let me know if I need to do some changes before merging.
> Fix Bug: ensure => absent was not working on nginx::resource::location

- manifests/resource/location.pp
- templates/vhost/location.erb
- templates/vhost/locations/alias.erb
- templates/vhost/locations/directory.erb
- templates/vhost/locations/fastcgi.erb
- templates/vhost/locations/proxy.erb
- templates/vhost/locations/stub_status.erb
- templates/vhost/locations/uwsgi.erb
Without this change, the structure of the templates for locations are
bit rigid and hard to understand.  Each component of a location uses an
isolated template which means that much of the common logic is hard
coded to a particular location style, the deployment of which is chosen
based on a somewhat arbitrary idea of what it means to be a location,
and in some cases, the module gets it wrong.  In cases where there is
seeming correctness, modifications to a particular selection of logic
are duplicated among the nested templates.
This work is the results of what was necessary for me to understand what
the templates were doing, and to deploy a fastcgi PHP application.  As
such, the templates have been centralized and conditions about their
functionality have been moved into the template to …
> Reorganize templates for clearer understanding

- manifests/package/debian.pp
- spec/classes/nginx_spec.rb
The nginx APT repository is currently not using https.
This PR will fix this.
> Use SSL for nginx APT repository

- manifests/resource/location.pp
See #971 
Fix the validation range for location's "priority" attribute to match docs. Using a higher value seems to cause unpredictable behavior.
> fix validation range for location priority

- manifests/config.pp
- manifests/init.pp
- spec/classes/nginx_spec.rb
- templates/conf.d/nginx.conf.erb
Add support for loader_files, loader_sleep and loader_threshold for proxy_cache_path.
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_path
```
Syntax:	proxy_cache_path path [levels=levels] [use_temp_path=on|off] keys_zone=name:size [inactive=time] [max_size=size] [manager_files=number] [manager_sleep=time] [manager_threshold=time] [loader_files=number] [loader_sleep=time] [loader_threshold=time] [purger=on|off] [purger_files=number] [purger_sleep=time] [purger_threshold=time];
Default:	—
Context:	http
```
Signed-off-by: Christophe Vanlancker <christophe.vanlancker@inuits.eu>
> Add support for proxy_cache_path loader directives

- manifests/init.pp
- manifests/package.pp
- manifests/package/debian.pp
- manifests/package/redhat.pp
- spec/classes/nginx_spec.rb
I'd have to integrate this into #938, but needed this Right Now at work, and thought I'd add it in.
Basically, the passenger and nginx versions for the passenger repo need to be in lockstep, or problems come up, and setting `package_ensure` for nginx without being able to lock passenger version too causes some problems.
> add passenger_package_ensure parameter to allow pinning passenger version

- manifests/resource/location.pp
> Remove unused variables

- manifests/resource/location.pp
- manifests/resource/server.pp
- spec/defines/resource_location_spec.rb
- spec/defines/resource_server_spec.rb
This attempts to resolve #1002 (but curious if anyone knows why the permissions on `fastcgi_params` and `uwsgi_params` were 0770 and 0660 respectively, rather than 0644 or 0444).
> Permissions on fastcgi_params and uwsgi_params files (#1002)

- spec/defines/resource_server_spec.rb
- templates/server/server_header.erb
- templates/server/server_ssl_header.erb
Not sure how 
https://github.com/voxpupuli/puppet-nginx/blob/master/spec/defines/resource_server_spec.rb#L1197-L1227
passes either before / after, but this seems to pass tests. I'm going to mark this as in-progress, though.
> Use double, vs single quotes around add_header values (#991)

- manifests/config.pp
- manifests/init.pp
- manifests/resource/geo.pp
- manifests/resource/map.pp
- manifests/resource/streamhost.pp
- manifests/resource/upstream.pp
- manifests/resource/upstream/member.pp
- spec/classes/nginx_spec.rb
- spec/defines/resource_map_spec.rb
> replace validate_* with datatypes

- manifests/init.pp
- spec/classes/nginx_spec.rb
Set mailhosts default value. This is useful when setting the SSL settings on multiple ports and protocols or disable xclient.
Similar to this commit for vhost (aka servers):
https://github.com/voxpupuli/puppet-nginx/commit/ad391f67bf5297f472bf7ccdd163dc7899dbe1fd
> Adds hiera nginx_mailhosts_defaults like nginx_servers_defaults

- manifests/package/debian.pp
- spec/classes/nginx_spec.rb
Updated to resolve #995 for new apt usage.
> Switched apt::source key from string to hash.

- manifests/init.pp
- manifests/package/debian.pp
- manifests/resource/server.pp
- spec/classes/nginx_spec.rb
- spec/defines/resource_server_spec.rb
Add the fastcgi index to the server resource
> Add fastcgi index

- manifests/params.pp
- spec/classes/nginx_spec.rb
This resolves #988 and also drops setting `manage_repo` for v5, for consistency with the rest of the module.
This doesn't really change much, just toggles the `manage_repo` flag.
> set manage_repo for Oracle "RedHat" (and not 5.x for any flavor anymore, for consistency with rest of module)

- manifests/resource/location.pp
- spec/defines/resource_location_spec.rb
Relates to https://github.com/voxpupuli/puppet-nginx/issues/1074
> Remove location check of some random values to be set in the context of location

- manifests/resource/server.pp
- spec/defines/resource_server_spec.rb
Fixes #1029
I'm pretty sure this is sane behaviour. Any thoughts?
> Avoid spurious location block when redirecting to SSL in another server block

- manifests/resource/server.pp
- spec/defines/resource_server_spec.rb
See #1015 
I would appreciate review on this... I'm not totally sure why these tests exist, or why there appear to be 2 sets of identical tests there:
https://github.com/voxpupuli/puppet-nginx/blob/master/spec/defines/resource_server_spec.rb#L1019-L1057
vs, say, https://github.com/voxpupuli/puppet-nginx/blob/master/spec/defines/resource_server_spec.rb#L1071-L1086
or what the use case is for having `ssl_port` == `listen_port` when `ssl` is _not_true, but I think this PR might make some sense.
> warn if $ssl=false but $ssl_port == $listen_port (#1015)

- manifests/resource/location.pp
- manifests/resource/server.pp
- spec/defines/resource_location_spec.rb
- spec/defines/resource_server_spec.rb
- templates/server/fastcgi.conf.erb
- templates/server/locations/fastcgi.erb
- templates/server/uwsgi_params.erb
Per various discussions (#862), use nginx shipped defaults for fastcgi_params / uwsgi_params. 
Obsoletes #855, etc.
I think long-term, we still may need a way to make this more customizable, but I think we have signoff in principle on at least pulling in the current vendor defaults from 1.10 / 1.11.
> Use nginx defaults for fastcgi_params / uwsgi_params

- manifests/init.pp
- manifests/resource/server.pp
- spec/classes/nginx_spec.rb
- spec/defines/resource_server_spec.rb
By adding location defaults it's possible to overwrite location
value like 'index_files'.
Related to #1068
> Add location defaults to init and server resource

- templates/server/server_header.erb
If `ssl_redirect` is enabled along with `rewrite_www_to_non_www`, then the user is redirected from the www version, to the http non-www one, and finally to https.
> Use correct scheme with rewrite_www_to_non_www

- manifests/resource/server.pp
- spec/defines/resource_server_spec.rb
- templates/server/server_header.erb
- templates/server/server_ssl_header.erb
> Allow index_files => undef in resource::server class

- metadata.json
This bumps the dependency on puppetlabs-concat to v3.0.0 and raises the minimum versions of the following dependencies to match:
* puppet:            4.6.1 -> 4.7.0
* puppetlabs-stdlib: 4.6.0 -> 4.13.1
> Bump puppetlabs-concat, puppetlabs-stdlib and Puppet minimum versions

- README.md
- metadata.json
I think this request makes some sense given the styleguide reference in #1086; this seems like a reasonable way to implement it, I think?
> make apt a soft dependency per styleguide (resolves #1086)

- manifests/resource/server.pp
- spec/defines/resource_server_spec.rb
While this doesn't seem like a super big deal (#1103), I agree with the proposed fix, and it's pretty easy to implement and to test for.
> Ensure absent on concat resource for server resource with ensure => absent (#1103)

- metadata.json
I think this should resolve #1107, as I'm guessing the module will still work w/ v 5.0.0, but let's see how the tests look.
> bump concat to <5.0.0 instead of <4.0.0 (#1107)

- manifests/package/debian.pp
Without this change, the nginx https repository url is added to sources.list.d
and apt-get update is executed immediately after, failing because
apt-transport-https is not yet installed. Subsequently all package
installs fail because the apt cache has been invalidated.
With this change we ensure the apt-transport-https package is present
before running apt-get update. Since all sources are now https, the
package is always necessary, which is why I moved it out of the 'case'
statement.
> Fix dependency on apt-transport-https

- templates/server/server_ssl_header.erb
Hi,
Juste fix a bad indent:
```DIFF
--- /etc/nginx/sites-available/myvhost.conf	2017-09-07 15:15:15.643976037 +0200
+++ /tmp/puppet-file20170907-746-127bflk	2017-09-07 15:15:36.412100955 +0200
@@ -26,7 +26,7 @@
ssl_prefer_server_ciphers on;
auth_basic                "Vhost authentification";
-      auth_basic_user_file      "/etc/nginx/.vhost-htpasswd";
+    auth_basic_user_file      "/etc/nginx/.vhost-htpasswd";
index  index.html index.htm index.php;
```
> Fix indent auth_basic_user_file ssl server

- manifests/resource/geo.pp
- manifests/resource/location.pp
- manifests/resource/mailhost.pp
- manifests/resource/map.pp
- manifests/resource/server.pp
- manifests/resource/streamhost.pp
- manifests/resource/upstream.pp
- manifests/resource/upstream/member.pp
Because the `ngnix::resource:*` types access ::ngnix class
parameters the nginx class needs to be declared before calling
the defined type.
`include ::nginx` inside the defined type is not enough because
params are evaluated before include is parsed.
Two of the defined types only access params inside. The include
way would work there - but for consistency I also added the fail.
Closes #983
> Fail defined types if nginx class was not declared before

- manifests/resource/location.pp
- manifests/resource/server.pp
- spec/defines/resource_location_spec.rb
- spec/defines/resource_server_spec.rb
This is just test fixes so far.
> Remove Optional for index_files (#1128)

- manifests/config.pp
- manifests/init.pp
- spec/classes/nginx_spec.rb
- templates/conf.d/nginx.conf.erb
Hello,
in a problem I was trying to solve with your module today, I needed to specify both `user` and `group` name for the nginx.conf `name` descriptor, as these were not the same. Simply setting the `daemon_user` param to `$user $group` doesn't work, because it is used below in config.pp as an owner for multiple directories:
```
file { $log_dir:
ensure => directory,
mode   => $log_mode,
owner  => $daemon_user,
group  => $log_group,
}
```
Therefore I believe I had to add this parameter, which fixes this issue nicely.
> add settable nginx daemon group

- lib/facter/nginx_version.rb
Cisco Nexus Switches may run older version of NGINX internally in which the command 'nginx -v' disables the nxapi socket (deletes sock file) on second or later runs.  Tested on CIsco NXOS 9k physical and virtual, and confirmed with Cisco engineers. 
Nginx is an underlying component, and should not be managed by resources other than the Cisco module(s) for the Nexus devices, hence prevention of this fact running on the Nexus operating system.
> Confine NGINX version fact to exclude Cisco Nexus switches

- docs/quickstart.md
Just a very small correction for consistency within the doc.
> Doc-only: Fix proxy/blog location reference

- manifests/resource/map.pp
- spec/defines/resource_map_spec.rb
- templates/conf.d/map.erb
As requested in previous PR (#1145) I've splitted features in multiples branches and PR:
Hello,
I needed to use the include directive in a map block to handle some redirections that were dynamically generated by an other app. I noticed this feature was missing from your module so I've added it.
Best Regards
François.
> adding support for include directive in map

- manifests/init.pp
- manifests/service.pp
- spec/classes/nginx_spec.rb
This allows to specify a custom service name such as 'custom-nginx', while also separately controlling the system nginx service outside of puppet-nginx module.
Closes #1158
> Use $service_name for service resource title.

- manifests/resource/location.pp
- spec/defines/resource_location_spec.rb
- templates/server/location.erb
- templates/server/locations/headers.erb
As well as in a server context, add_header is also valid in a location.
See
http://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header
> Add add_header parameter to location

- README.md
- manifests/package/debian.pp
It's better to have this handled in puppetlabs-apt since this will also work for Debian 10 which has removed the apt-transport-https package.
> Compatibility with puppetlabs-apt 4.4.0

- templates/server/locations/fastcgi.erb
Fix syntax error in ERB template for fastcgi location.
This commit fixes a syntax error in the generated ruby script of this erb file.
Using ruby version `2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]` and erb version `erb.rb [2.1.0 2017-12-22]`, the erb template was being converted into the following ruby code:
```
if defined? @fastcgi_script 
);  @fastcgi_param = { 'SCRIPT_FILENAME' => @fastcgi_script }.merge(@fastcgi_param || {}) 
end 
```
which resulted in the following error when doing a syntax check with `ruby -c`:
```
-:19: syntax error, unexpected ')'
);  @fastcgi_param = { 'SCRIPT...
^
```
With this commit applied, the converted ruby code will look like this:
```
if defined? @fastcgi_script
_erbout.<<(-"    "); _erbout.<<(-"\n"
);  @fastcgi_param = { 'SCRIPT_FILENAME' => …
```
> Fix syntax error in ERB template for fastcgi location.

- spec/defines/resource_server_spec.rb
- templates/server/server_header.erb
The server resource has an ```autoindex``` parameter but the templates did not reflect this. There was also no testcase for this parameter.
> add missing autoindex parameter in template of server resource

- manifests/resource/server.pp
> Adding proxy send timeout for the nginx server configuration.

- manifests/config.pp
- manifests/init.pp
- spec/classes/nginx_spec.rb
- templates/conf.d/nginx.conf.erb
This change adds support for enabling/disabling the etag nginx directive in the http context. http://nginx.org/en/docs/http/ngx_http_core_module.html#etag
If no value is supplied it will not add anything and allow the nginx-defined default to take effect.
> add etag support at the http level

- .msync.yml
- .sync.yml
- .travis.yml
- Gemfile
- spec/acceptance/nodesets/fedora-26-x64.yml
- spec/acceptance/nodesets/fedora-27-x64.yml
> modulesync 1.18.0 & enhance acceptance test matrix

- spec/classes/nginx_spec.rb
> Fix #1190 Accommodate default package name nginx-mainline for Arch Linux

- manifests/resource/server.pp
- spec/defines/resource_server_spec.rb
- templates/server/server_ssl_settings.erb
Copied from mailhost resource. Needed to get 100 on key exchange on SSL Labs.
> Add ssl_ecdh_curve to server resource

- spec/defines/resource_server_spec.rb
- templates/server/server_header.erb
This fixes the indenting of the autoindex parameter in the server template to be consistent with all the other parameters at the server level.
```
server {
listen *:80; 
server_name           example.com;
root /usr/local/www/example.com/; 
return 301 https://$host$request_uri;
autoindex off; 
access_log            /var/log/nginx/example.com_redirect.access.log combined;
error_log             /var/log/nginx/example.com_redirect.error.log;
}
```
```
server {
listen *:80; 
server_name           example.com;
root /usr/local/www/example.com/; 
return 301 https://$host$request_uri;
autoindex off; 
access_log            /var/log/nginx/example.com_redirect.access.log combined;
error_log             /var/log/nginx/example.com_redirect.error.log;
}
```
> Fix indent of autoindex param in server template

- .sync.yml
- .travis.yml
- manifests/init.pp
- manifests/package/debian.pp
- manifests/params.pp
- metadata.json
- spec/acceptance/class_spec.rb
- spec/acceptance/nginx_server_spec.rb
This is a rebase of https://github.com/voxpupuli/puppet-nginx/pull/1154
> Add Debian 9 support

- README.md
Fix readme example for streamhosts using Hiera. It incorrectly states that listen_port is a string value when using hiera.
Using the example hiera data for streamhosts gives the following error:
```
[root@nginxlbmasters /]# puppet agent -t
Info: Using configured environment 'kubernetes'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Nginx::Resource::Streamhost[kubernetes-api-streamhost]: parameter 'listen_port' expects an Integer value, got String (file: /etc/puppetlabs/code/environments/kubernetes/modules/nginx/manifests/init.pp, line: 181) on node …
```
> Update readme: listen_port is integer for Hiera

- metadata.json
Updates minimum version of stdlib to 4.22.0, which includes support for the Stdlib::Filemode type.
This type will be used in the process of adding types to all parameters (#1189).
> Update minimum version of puppetlabs/stdlib to 4.22.0

- manifests/resource/server.pp
- spec/defines/resource_server_spec.rb
- templates/server/server_ssl_settings.erb
This adds support for specifying the `ssl_verify_depth` option in server sections.
> Support setting `ssl_verify_depth` in nginx::resource::server

- manifests/init.pp
- manifests/package/redhat.pp
The idea is that people can switch between the different available nginx
repos. in case somebody switched from the passenger one to the upstream
repo we want to purge the passenger repo. However this gets us intro
trouble if the person never switched, but another module declares a
resource with this name.
> allow people to not purge passenger yumrepo

- manifests/config.pp
- manifests/init.pp
- spec/classes/nginx_spec.rb
- templates/conf.d/nginx.conf.erb
Allow nginx to load dynamic modules by specifying an absolute or a
relative ("modules/") path. Modules must be installed separately and
before loading the puppet nginx module.
> Add support for dynamic modules.

- manifests/init.pp
- manifests/params.pp
- manifests/resource/server.pp
- spec/defines/resource_server_spec.rb
- templates/server/server_ssl_settings.erb
fixes #1224. the option 'ssl on' within a server block is deprecated since nginx 1.15.0.
> dont deploy "ssl on" on nginx 1.15 or newer

- manifests/init.pp
- manifests/service.pp
- spec/classes/nginx_spec.rb
Adds an explicit $service_enable parameter. Sets to undef by default, which then follows the previous behaviour of auto-setting from $service_ensure.
This replaces a previous effort #1211
Fixes #1208
> Add service_enable and simplify service_ensure, #1208

- manifests/package/redhat.pp
- spec/classes/nginx_spec.rb
Use HTTPS instead of HTTP for yum repositories
None. I actually implemented it because I use this module from a location where only HTTPS is required, but it's good practice to use HTTPS when available anyway!
> Use HTTPS for Yum repositories

- manifests/resource/server.pp
very critical change, fixes a typo in the server resource
> fix typo in resource/server.pp

- templates/conf.d/mime.types.epp
This ensures there are no empty lines in the file.
> Strip line endings in mime.types

- manifests/config.pp
- manifests/init.pp
The template already allowed setting it to false. This completes it.
> Propery handle ${client_body,proxy}_temp_path

- .fixtures.yml
- .github/CONTRIBUTING.md
- .msync.yml
- .travis.yml
- Gemfile
- metadata.json
> modulesync 2.1.0 and  allow puppet 6.x

- spec/classes/nginx_spec.rb
- templates/conf.d/nginx.conf.erb
> Move error_log to the http section

- manifests/init.pp
Many people are confused by this default setting. The default of one
core is often a bottleneck. I would like to switch the default to the
amount of cores.
> start one worker process per core

- manifests/params.pp
Seems about a week ago, $log_user parameter got added, and that broke OpenBSD, since no user 'nginx' exists. Log user is 'www', same as $daemon_user.
Therefore add $log_user to the module_os_overrides section for OpenBSD.
Fixes #1259
> add the log_user with proper value to OpenBSD override section.

- manifests/params.pp
This PR sets the default log user for Archlinux to `http`, the same user the daemon is running with.
The log user being set to `nginx` by default on Archlinux. That user does not exist (contrary to `http`), therefore Puppet wail fail to apply the ownership of the log directory.
> Archlinux: Set default log user to http

- README.md
Change the example of declaring the nginx class in the README to use `include`.
There's really no reason to use the resource-like declaration when
you're not specifying any class parameters. It's cleaner and safer to
use `include`.
> Improve example of quick install in README

- manifests/init.pp
- spec/classes/nginx_spec.rb
> Change gzip default to off and update tests

- spec/defines/resource_location_spec.rb
- spec/defines/resource_server_spec.rb
- templates/server/locations/headers.erb
- templates/server/server_header.erb
- templates/server/server_ssl_header.erb
Allows any combination of add_headers quoting.
_This solves issues highlighted in #991 #992 #1020_ 
**Double Quotes:**
```
add_header => {
'Access-Control-Allow-Origin'      => '*' , 
}
```
would produce
`  add_header              "Access-Control-Allow-Origin" "*";`
**Double Quotes and Unquoted**
```
add_header => {
'Access-Control-Allow-Origin'      => {'*' => 'always'}, 
}
```
would produce
`  add_header              "Access-Control-Allow-Origin" "*" always;`
**Custom Quotes**
```
add_header => {
'Access-Control-Allow-Origin'      => {'' => '\'*\' always'}, 
}
```
would produce
`  add_header              "Access-Control-Allow-Origin" '*' always;`
> Allow setting unquoted or custom flags on add_headers

- manifests/resource/location.pp
- spec/acceptance/nginx_location_spec.rb
- spec/defines/resource_location_spec.rb
By changing the data type, you can now specify multiple servers for
a location. These are then rolled out in a loop. This doesn't break existing installations.
Fixes GH-1187
> Allow multiple servers per location

- spec/defines/resource_server_spec.rb
- templates/server/server_ssl_header.erb
Hello,
the option autoindex was missing in server_ssl_header.erb. 
Thanks!
> Add autoindex to ssl_header too

- manifests/resource/upstream.pp
The condition which decides if we have upstream members configurred or
if we import from PuppetDB was wrong. Even if no upstream members are
defined the condition was true. As a result, you couldn't import upstream
members no matter what you configured. Sorry for that
Fixes GH-1274
> Fix the condition for upstream members

- manifests/params.pp
Update SmartOS support, which is in the Solaris family.
```
facter -p os
{"name"=>"SmartOS", "family"=>"Solaris", "release"=>{"minor"=>"11", "full"=>"5.11"}}
```
SmartOS is in the Solaris family, so was never reaching the `$facts['os']['family']` default case, but instead landing in Solaris.
In addition, `/usr` is read-only on SmartOS, but not Solaris.
Tested on a Base-64 17.4.0-LTS zone, initially setup by 0.9.0 version of this module.
> Update smartos support

- manifests/config.pp
- manifests/init.pp
- manifests/resource/location.pp
- manifests/resource/server.pp
- spec/classes/nginx_spec.rb
- spec/defines/resource_location_spec.rb
- templates/conf.d/nginx.conf.erb
- templates/server/locations/proxy.erb
We want to be able to manage the following (optional) configuration values:
[proxy_busy_buffers_size](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_busy_buffers_size)
[proxy_max_temp_file_size](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_max_temp_file_size)
With this PR user can modify the above values inside the location-block and also in the main nginx.conf.
Fixes #1176
> Introduce two new optional proxy parameters

- manifests/params.pp
Fixes for:
Error: Could not find user nginx
Error: /Stage[main]/Nginx::Config/File[/var/log/nginx]/owner: change from root to nginx failed: Could not find user nginx
On FreeBSD/DFLY default log owner is root
> overwrite FreeBSD and DragonFlyBSD log_user

- manifests/init.pp
- manifests/package/debian.pp
- metadata.json
- spec/classes/nginx_spec.rb
repo_source enables you to set a custom url for the Debian repo.
Unit
This allows you to use your own repo to install Nginx or to use http and cache the packages on your local network.
> add repo_source for custom Debian repo

- types/upstreammemberdefaults.pp
I don't see a reason, why server shouldn't be a parameter which gets set within member_defaults, e.g. if only the port is changing, this makes the manifest a little bit easier.
> Param server might also be a default upstream param

- manifests/resource/server.pp
- spec/defines/resource_server_spec.rb
If you define a file to create the SSL key and/or cert then these should
be in place before nginx uses them. This prevents writing out a
configuration that will not start.
Fixes #1295
> Automatically require SSL cert files in the server

- manifests/init.pp
- Added hiera defaults configuration options for all resources
- Sorted variables
- Casted them to an hash
> Add hiera defaults configuration options for all resources

- manifests/init.pp
In my understanding, $nginx_upstream_defaults should be of type UpstreamDefaults, not UpstreamMemberDefaults
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Class[Nginx]: parameter 'nginx_upstream_defaults' unrecognized key 'member_defaults' at /etc/puppetlabs/code/environments/production/private_modules/profile/manifests/nginx.pp:53:3 on node host.example.com
```
> Fix `$nginx_upstream_defaults` type

- spec/acceptance/nginx_mail_spec.rb
- spec/defines/resource_mailhost_spec.rb
- templates/mailhost/mailhost.erb
- templates/mailhost/mailhost_ssl.erb
The `ssl` on syntax is deprecated since nginx 1.15.
This PR fixes it for mailhost.
fixes #1284
> dont deploy "ssl on" on nginx 1.15 or newer (for mailhost)

- examples/snippet.pp
- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- manifests/resource/snippet.pp
- spec/defines/resource_snippet_spec.rb
- templates/snippet/snippet_header.epp
Add basic support for creating snippets (reusable configuration files) that can be included by other resources. In phase 1 of this effort I am just introducing the ability to create include files by providing the raw contents, but future phases will include writing server::resource::location output into a snippet for reusability.
Please let me know your thoughts on the direction this is going.
Fixes #644
Fixes #1135
> initial support for snippets

- README.md
https://github.com/voxpupuli/puppet-nginx/pull/1233 was a breaking
change that amongst other things, renamed this parameter.
Fixes #1316
> Fix `upstream_context` parameter in README

- .sync.yml
- .travis.yml
- manifests/params.pp
- metadata.json
- spec/acceptance/class_spec.rb
> add ubuntu1804 as supported OS

- manifests/config.pp
- manifests/init.pp
- spec/classes/nginx_spec.rb
- templates/conf.d/nginx.conf.erb
In certain environment the user may wish to use mime.types file from
a path other than $conf_dir.
For example when using `conf_dir => '/mnt/gluster/nginx'` and mounting the path into a container at `/etc/nginx`.
The module needs to know the 'real' configuration path because it has to write the files there, but at the same time it can't use this path to substitute the absolute path of the mime.types file, because it is at a different location in the container (here: `/mnt/gluster/nginx/mime.types` vs. `/etc/nginx/mime.types`)
> Allow setting a custom path for mime.types

- .msync.yml
- .travis.yml
- Dockerfile
- Gemfile
- Rakefile
- examples/init.pp
- examples/location_alias.pp
- examples/location_params.pp
- examples/server.pp
- examples/server_ssl.pp
- examples/upstream.pp
Includes https://github.com/voxpupuli/modulesync_config/pull/565
> Modulesync 2.6.1 with local changes

- README.md
- manifests/init.pp
- manifests/params.pp
- manifests/resource/server.pp
- spec/acceptance/nginx_mail_spec.rb
- spec/acceptance/nginx_server_spec.rb
- spec/defines/resource_mailhost_spec.rb
- templates/mailhost/mailhost.erb
- templates/mailhost/mailhost_ssl.erb
- templates/server/server_ssl_settings.erb
Nginx 1.16 has recently been released.  Instead of updating the README
to recommend users set the `add_listen_directive` parameter, this
parameter has been replaced by an `nginx_version` parameter that
defaults to the fact (if available).  If the fact isn't available, it
defaults to a very conservative `1.6.0` (the version that ships in Debian
8).  Future enhancements could make the non-fact default be OS specific.
> Replace `add_listen_directive` with `nginx_version`

- manifests/resource/server.pp
- spec/defines/resource_server_spec.rb
- templates/server/server_header.erb
- templates/server/server_ssl_header.erb
This adds the opposing configuration to `rewrite_www_to_non_www`. Many site owners prefer (and this is not to get into the discussion of who is right or wrong) site urls to begin `www.` but also want a rewrite from non-`www.` for SEO purposes.
This PR adds `rewrite_non_www_to_www`, defaulting to false as per the existing param.
> Add rewrite_non_www_to_www option

- manifests/resource/server.pp
- spec/acceptance/nginx_server_spec.rb
- spec/spec_helper_acceptance.rb
- templates/server/server_ssl_settings.erb
This pull request adds support for the ssl_password_file directive of nginx. This directive is needed, if the ssl key file is password encrypted (should be standard nowadays).
n/a (I didn't create an issue first but tried to not only raise a request but also deliver the solution)
> Add ssl_password_file directive to support encrypted ssl keys

- spec/acceptance/nginx_server_spec.rb
- spec/defines/resource_server_spec.rb
- templates/server/server_header.erb
Fixes GH-1347
This makes it possible to define locations that are accepted over HTTP and only forward everything else to HTTPS. This allows, for example, to configure something like this:
```
nginx::resource::server { 'www.puppetlabs.com':
ensure       => present,
ssl          => true,
ssl_cert     => '/etc/pki/tls/certs/blah.cert',
ssl_key      => '/etc/pki/tls/private/blah.key',
ssl_redirect => true,
www_root     => '/var/www/www.puppetlabs.com',
}
nginx::resource::location { 'letsencrypt':
location    => '^~ /.well-known/acme-challenge/',
www_root    => '/var/www/letsencrypt',
index_files => [],
ssl         => false,
server      => ['www.puppetlabs.com'],
}
```
Which results in a server accepting LetsEncrypt Challanges on HTTP and redirect everything else to HTTPS.
Fixes #1347
> Move ssl_redirect into a location

- manifests/params.pp
- spec/classes/nginx_spec.rb
I am not sure if it's correct anywhere else, but at the very least on
Debian, the "run dir" is *not* /var/nginx, but /var/run/nginx. That
seems like a better default everywhere, but I'm just going to scratch
that itch for now.
Ideally, this would actually be in /run/nginx since that's the new
standard (and the default in the Debian package), but I suspect this
will not work properly in older Debian releases (e.g. 7) still marked
as supported here.
This is important because /var is a real, on-disk, filesystem while /var/run points to /run which is a tmpfs, and therefore much faster.
This is a WIP because I suspect tests will fail with just this naive commit, but gotta start the conversation somewhere.
> Debian run_dir should be in /var/run/nginx

- metadata.json
Somewhere in the refactoring we lost this. This module always supported
CentOS6/7.
> CentOS: Add it back to metadata.json

- spec/classes/nginx_spec.rb
- spec/defines/resource_geo_spec.rb
- spec/defines/resource_location_spec.rb
- spec/defines/resource_mailhost_spec.rb
- spec/defines/resource_map_spec.rb
- spec/defines/resource_server_spec.rb
- spec/defines/resource_snippet_spec.rb
- spec/defines/resource_stream_spec.rb
- spec/defines/resource_upstream_spec.rb
- spec/spec_helper.rb
Getting the correct facter version is tricky. We use facterdb as a source to mock facts see https://github.com/camptocamp/facterdb. People might provide a specific facter version.  In that case we use it. Otherwise we need to match the correct facter version to the used puppet version. As of 2019-10-31, puppet 5 ships facter 3.11 and puppet 6 ships facter 3.14 (see https://puppet.com/docs/puppet/5.5/about_agent.html).
> Mock facter version based on puppet version & unit tests: print puppet/facter version

- spec/defines/resource_server_spec.rb
- templates/server/server_ssl_header.erb
This part seems to be missing from the original patch to add support for `rewrite_non_www_to_www` (4b2b108c28d778b5250bf126b5f8aacef6b98858).
It was added to the non-SSL template but missing from the SSL template.
n/a (no issue reported)
> Fix rewrite_non_www_to_www when using SSL

- manifests/config.pp
- manifests/init.pp
- manifests/resource/location.pp
- spec/classes/nginx_spec.rb
- spec/defines/resource_location_spec.rb
- templates/conf.d/nginx.conf.erb
- templates/server/location_header.erb
Add support for `limit_req_zone` in main nginx config and `limit_req`
for `nginx::resource::location`.
In init.pp
`limit_req_zone` can be a String, or an array of String
In resource/location.pp
`limit_zone` can be a String and should point to a zone defined from
`limit_req_zone` in init.pp
> Add support for limit_req_zone in main nginx config and limit_req: Fixes #1134

- .github/CONTRIBUTING.md
- .sync.yml
- .travis.yml
- manifests/params.pp
- metadata.json
- spec/acceptance/class_spec.rb
Nginx official repo supports Debian 10, see here: http://nginx.org/packages/debian/dists/
Systems that upgraded to buster already are not receiving updates for nginx right now.
> manage repo for Debian 10

- manifests/config.pp
- manifests/init.pp
- manifests/package/debian.pp
- manifests/package/redhat.pp
- manifests/params.pp
- spec/acceptance/class_spec.rb
- spec/classes/nginx_spec.rb
- templates/conf.d/nginx.conf.erb
This is a follow-up to #1341 (closed without being merged) which was an attempt to fix #1340. I took the commits in this legacy PR, rebased them on top of master (fixing a bunch of conflicts) and am now fixing the CI.
Fixes #1340
> Manage libnginx-mod-http-passenger on modern Debian / Ubuntu

- manifests/resource/location.pp
- manifests/resource/server.pp
- spec/defines/resource_location_spec.rb
- templates/server/locations/proxy.erb
add proxy_request_buffering parameter to location & vhost
> add proxy_request_buffering parameter to location & vhost

- .sync.yml
- .travis.yml
- Gemfile
- manifests/params.pp
- metadata.json
- spec/acceptance/class_spec.rb
It's currently in extended support time and even that ends in about a
month.
> Drop Debian 8 support

- manifests/resource/map.pp
- spec/defines/resource_map_spec.rb
Location for mapfiles differ if mapfile is loaded in http or stream context.
https://github.com/voxpupuli/puppet-nginx/issues/1378
> Use correct stream mapfile location

- manifests/config.pp
- manifests/init.pp
- manifests/resource/location.pp
- manifests/resource/server.pp
- spec/classes/nginx_spec.rb
- spec/defines/resource_location_spec.rb
- spec/defines/resource_server_spec.rb
- templates/conf.d/nginx.conf.erb
- templates/server/location.erb
- templates/server/locations/gzip.erb
- templates/server/server_header.erb
- templates/server/server_ssl_header.erb
This PR extends https://github.com/voxpupuli/puppet-nginx/pull/1318 with tests and the setting on server and location level.
Not sure how to commit into foreign PRs.
No issue reported.
> add static gzip support

- manifests/resource/geo.pp
- manifests/resource/location.pp
- manifests/resource/mailhost.pp
- manifests/resource/map.pp
- manifests/resource/server.pp
- manifests/resource/upstream.pp
Changed the 'file' resources mode to use $nginx::global_mode to keep permissions consistent and secure
n/a
> Ensured file mode permissions are more consistent

- manifests/resource/mailhost.pp
- spec/defines/resource_mailhost_spec.rb
Apply the mailhost resource parameter ensure to the concat resource.
Fixes #1394
> Actually use the ensure parameter for mailhost resource to provide absent support

- Gemfile
- manifests/package/redhat.pp
- spec/acceptance/class_spec.rb
- spec/classes/nginx_spec.rb
without this change, we see the following error since november 2019:
```
passenger/7/x86_64/
Retrieving key from https://packagecloud.io/phusion/passenger/gpgkey
passenger/7/x86_64/
https://oss-binaries.phusionpassenger.com/yum/passenger/el/7/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for passenger
Trying other mirror.
```
> Update passenger rpm gpg key

- manifests/resource/mailhost.pp
* Remove what looks like copy-n-pasted lines (copied from resource/server.pp ?)
* Use `Stdlib::Port` instead of `Integer`
> Minor refactor of mailhost.pp

- manifests/resource/geo.pp
- manifests/resource/map.pp
- manifests/resource/streamhost.pp
Resource defaults outside of site.pp are not recommended.
https://puppet.com/docs/puppet/6.18/lang_defaults.html
In these cases, there was only a single file resource in each manifest.
> Refactor to remove some `File` defaults

- manifests/config.pp
- manifests/init.pp
- spec/classes/nginx_spec.rb
- spec/type_aliases/debugconnection_spec.rb
- templates/conf.d/nginx.conf.erb
- types/debugconnection.pp
Addes a possibility to use [debug_connection](http://nginx.org/en/docs/ngx_core_module.html#debug_connection) under events. 
n/a
> Add debug_connection events option

- spec/defines/resource_stream_spec.rb
- templates/streamhost/streamhost.erb
When declaring nginx::resource::streamhost, there is the ability to add a "resolver" option, but this is not actually honoured in the configuration, a section to test the existence of that Variable and define it in the configuration erb file is needed.
```
nginx::resource::streamhost {'test':
...
resolver => ['255.255.255.255'],
...
}
```
should create a file in /etc/nginx/conf.stream.d/XXX-test.conf
which contains
```
server {
...
resolver 255.255.255.255;
...
}
```
but currently does not, this code ensures this entry is present.
When declaring the parameter resolver as per
```
```
for a streamhost, nothing is actually configured.
> Adding resolver entries to streamhost.erb

- manifests/init.pp
- manifests/service.pp
- spec/classes/nginx_spec.rb
It's valid to pass in undef values. That makes the OpenBSD check redundant. The same goes for the restart command. That removes pretty much all logic so there is no more benefit to having class parameters. That's why it now uses all the variables directly from the nginx class. The has{status,restart} parameters default to true since Puppet 2.7 so they can be removed.
Replaces https://github.com/voxpupuli/puppet-nginx/pull/1209
> Simplify service class

- templates/server/locations/headers.erb
Line up `add_header` with surrounding params
n/a
```
--- /etc/nginx/sites-available/example.org.conf	2020-10-19 22:14:24.053208210 +0200
+++ /tmp/puppet-file20201019-28480-1vh74v	2020-10-19 22:16:05.452314220 +0200
@@ -6,7 +6,7 @@
server_name           example.org;
resolver                   8.8.8.8 8.8.4.4 valid=300s;
-    add_header "X-Frame-Options" "SAMEORIGIN";
+  add_header "X-Frame-Options" "SAMEORIGIN";
return 301 https://$host:443$request_uri;
access_log            /var/log/nginx/access.log combined;
@@ -34,7 +34,7 @@
resolver                   8.8.8.8 8.8.4.4 valid=300s;
access_log            /var/log/nginx/ssl-access.log combined;
error_log             /var/log/nginx/ssl-error.log;
-    add_header "X-Frame-Options" "SAMEORIGIN";
+  add_header "X-Frame-Options" "SAMEORIGIN"; …
```
> Indentation fix for location template

- spec/defines/resource_location_spec.rb
- templates/server/location_header.erb
Enabling defining 'location_allow's content as nested arrays.
Mostly useful when using Hiera to merge arrays from different hierarchy levels.
> Add `.flatten` to `location_allow` to enable using nested arrays

- manifests/config.pp
- manifests/init.pp
- manifests/resource/geo.pp
- manifests/resource/location.pp
- manifests/resource/mailhost.pp
- manifests/resource/map.pp
- manifests/resource/server.pp
- manifests/resource/snippet.pp
- manifests/resource/streamhost.pp
- manifests/resource/upstream.pp
- manifests/service.pp
- spec/acceptance/init_spec.rb
This implements a switch to enable the nginx config check via `nginx -t` on all config file changes. If the config check is enabled (disabled by default) and fails, the service refresh of nginx will be unscheduled b puppet.
No issue created, started directly with the feature.
> implement config check on config change before service restart

- templates/server/server_header.erb
- templates/server/server_ssl_header.erb
Introduced in !1417. The template server/locations/headers.erb is included in several other templates. At those templates the indention of the call is incorrect and leads to:
```
allow 10.129.14.49;
deny all;
gzip off;
-    add_header "Content-Type" "text/html";
-    add_header "Status" "406";
+  add_header "Content-Type" "text/html";
+  add_header "Status" "406";
root      /var/www/maintenance/scripts;
return 406 "[406] request is not acceptable
```
> Fix indention for add_header at template calls

- templates/server/locations/headers.erb
This reverts commit 79fd696271e03a513dd86e77f5a0567f0adb3bef.
The PR #1417 fixed the indention of `add_header` outside of location, but introduced the wrong indention within the locations. The right source to fix the indention outside of location has been fixed via PR #1424. Therefore we can revert the #1417 changes.
> Revert "Indentation fix" from #1417

- README.md
Github Actions is used by this module.
This way, the real build status is shown
> Replace Travis build status in README

- metadata.json
This PR drops Red Hat 6 and CentOS 6 from the metadata as those OS's are end of life and their yum repositories have been archived. It also raises the upper bounds of acceptable Puppet versions to include Puppet 7 and raises the lower bounds to Puppet 6.1 since Puppet 5 is also EoL.
> Drop EL6 & Puppet 5 from and add Puppet 7 to metadata

- manifests/config.pp
- manifests/init.pp
- spec/classes/nginx_spec.rb
- templates/conf.d/nginx.conf.erb
Adding two more lingering_ config options
lingering_close
lingering_time
See https://nginx.org/en/docs/http/ngx_http_core_module.html#lingering_timeout
n/a
> Add two more lingering_ config options

- manifests/params.pp
> Drop Ubuntu 10/12/14 code

- manifests/params.pp
- metadata.json
- spec/acceptance/class_spec.rb
- spec/classes/nginx_spec.rb
now that we dropped puppet 5 we can add ubuntu 20.04 support
> Add focal support

- manifests/init.pp
- manifests/service.pp
Right now, the service_config_check exec command is using `nginx -t` and there's no way to change it.
If you're running e.g. openresty, there's no `nginx` executable and the check will fail.
This PR adds a paramter `$nginx::service_config_check_command` with a default value of `nginx -t`
> makes service_config_check exec command configurable

- manifests/config.pp
- spec/classes/nginx_spec.rb
I get this on each run here:
Notice: /Stage[main]/Nginx::Config/File[/run/nginx/client_body_temp]/mode: mode changed '0700' to '0755'
Notice: /Stage[main]/Nginx::Config/File[/run/nginx/proxy_temp]/mode: mode changed '0700' to '0755'
It seems like nginx and this module have different opinions on the
correct mode for those directories. I believe Nginx is more correct,
and we should therefore follow it.
Note that this might apply to your module only if you have a global
File default resource defined.
Fixes: #1272
> use more restrictive mode on temp paths

- manifests/init.pp
- manifests/resource/server.pp
- spec/defines/resource_server_spec.rb
- templates/server/server_header.erb
- templates/server/server_ssl_header.erb
This PR unifies `nginx::http_log_format` and `nginx::resource::server::log_format` that the later defaults to the generic set default value.
If no generic default value is set nginx itself will default to the "old" default value of "combined" (see http://nginx.org/en/docs/http/ngx_http_log_module.html#access_log)
As there are already tests which test the behavior of `nginx::http_log_format` and `nginx::resource::server::log_format` there were no additional tests added.
Relates #773
> Unify (http_)log_format in nginx class and server resource

- manifests/resource/server.pp
With the merge of #1446 a change has been introduced, which changes permissions on the `ssl_key` and `ssl_cert` files.
This is due to resource defaults set in https://github.com/voxpupuli/puppet-nginx/blob/d51a170a413410b87124ab5ffb11f409c2727a56/manifests/resource/server.pp#L438-L447 and the way, resource dependency is set up in e.g. https://github.com/voxpupuli/puppet-nginx/blob/d51a170a413410b87124ab5ffb11f409c2727a56/manifests/resource/server.pp#L600-L602
If you're managing certificates and setting different owner and group, they will be changed to the user and group defined within this module, which isn't something expected.
None
> do not set resource defaults on ssl_cert/ssl_key resources

- manifests/init.pp
- manifests/resource/location.pp
- manifests/resource/server.pp
This PR introduces variables to overwrite the fastcgi.conf and uwsgi_params templates.
Relates to #862
> Add variables to overwrite fastcgi.conf and uwsgi_params template

- .github/workflows/ci.yml
- .sync.yml
- manifests/resource/mailhost.pp
- manifests/resource/server.pp
- manifests/resource/streamhost.pp
- spec/defines/resource_mailhost_spec.rb
in 99% of the deployments both ports are identical. to make this easier
for the users we can just tell puppet that the default value for
$ipv6_listen_port is the value of $listen_port. That makes it easier for
people that want their dual stack application to listen on a nonstandard
port. They only need to set it once.
> default ipv6_listen_port to listen_port

- spec/acceptance/init_spec.rb
- spec/acceptance/nginx_mail_spec.rb
These commits fix CI on CentOS 7 :tada: 
Management of the mail module can be improved in multiple way, but for now I focused on fixing CI so I just ensure that what is not managed by the module and is required is properly setup in the regression test suite.
The configuration of the mail module in CI now match the configuration I have in place for passenger which the module does not handle on CentOS.  We can probably improve this area in another PR to have the module able to have a similar behavior on CentOS and on Debian.
> Fix CI on CentOS 7

- manifests/init.pp
…le behind proxy therefore it makes sense to add it to the defaults
> Set X-Forwarded-Proto by default for reverse proxies

- manifests/init.pp
add create_resources for nginx_snippets and nginx_snippets_defaults
> Add create_resources for nginx_snippets

- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/nginx_spec.rb
- templates/conf.d/nginx.conf.erb
The [general description of `/run/`](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s15.html) is fairly vague and not in the original spec however my high level reading is that it relates more to small files which are used for service orchestration and not data (temporary or otherwise) which is specific to the programs operations for the later /var/lib which states the following seems more appropriate:
> Furthermore, this hierarchy holds state information pertaining to an application ....  State information is data that programs modify while they run, and that pertains to one specific host.
https://tldp.org/LDP/Linux-Filesystem-Hierarchy/html/Linux-Filesystem-Hierarchy.html#var
And as we see from the [debian packages](https://salsa.debian.org/nginx-team/nginx/-/blob/master/debian/rul …
> (1372) Drop run_dir and make client_body_temp_path/proxy_temp_path optional

- spec/acceptance/class_spec.rb
- spec/setup_acceptance_node.pp
This doesn't take care of EL7, which I haven't looked into yet. But it's progress.
> Fix acceptance tests on Arch and Ubuntu w/ Puppet 6

- manifests/config.pp
- manifests/init.pp
- spec/classes/nginx_spec.rb
do not recreate log_dir if it is already a symlink
> do not recreate log_dir if it is already a symlink

- manifests/package/redhat.pp
- manifests/params.pp
- metadata.json
Enable RHEL8 operatingsystem_support
> Add RedHat 8

- spec/defines/resource_location_spec.rb
- templates/server/locations/headers.erb
More and more security headers are JSON formatted documents.  With the hardcoded quotes, we have to think hard not to break the generated NGINX configuration.
Rely on Puppet programmatic string representation to avoid the end user to have to worry about escaping quotes.
If you manually escaped header contents before passing them to the module, you need to remove the extra escaping, e.g.:
```diff
diff --git a/site-modules/profile/functions/security_headers.pp b/site-modules/profile/functions/security_headers.pp
index c6087a2..ba6434d 100644
--- a/site-modules/profile/functions/security_headers.pp
+++ b/site-modules/profile/functions/security_headers.pp
@@ -27,9 +27,9 @@ function profile::security_headers(
x_content_type_options    => 'nosniff',
referrer_policy           => …
```
> Move header escaping responsibility from the end user to Puppet

- manifests/init.pp
- spec/classes/nginx_spec.rb
- templates/conf.d/nginx.conf.erb
- types/logformat.pp
NGINX can output logs in JSONL format.  This requires to set the escape
parameter to NGINX log_format, which the module does not currently
support.
Most users will not be affected, but if you customized the `escape` parameter with a `log_format` containing closing and opening quotes in the form `"escape=foo' 'actual_format"`, an update is required. e.g.:
```diff
diff --git a/site-modules/profile/manifests/nginx.pp b/site-modules/profile/manifests/nginx.pp
index 1fa15f7..3d5192f 100644
--- a/site-modules/profile/manifests/nginx.pp
+++ b/site-modules/profile/manifests/nginx.pp
@@ -109,7 +108,10 @@ class profile::nginx (
dynamic_modules           => $dynamic_modules,
log_mode                  => '0755',
log_format                => {
-      json_combined => "escape=json' '{${json_log.map …
```
> Allow to set log_format's "escape" parameter

- REFERENCE.md
- manifests/resource/mailhost.pp
- manifests/resource/server.pp
- manifests/resource/streamhost.pp
This was refering to issue #30 which was closed by changing the
behavior for *not* adding the default in the template. Instead, the
default includes the setting. We do not mention the default here
because it's visible in the generated `REFERENCE.md` file and is not
mentioned in other parameter documentation anyways.
> fix documentation about ipv6only always being added

- REFERENCE.md
- manifests/init.pp
- spec/classes/nginx_spec.rb
For compatibility with https://github.com/puppetlabs/puppetlabs-stdlib/pull/1196.
Fixes #1522.
> init: set package_ensure defaults to installed

- manifests/config.pp
- manifests/init.pp
- spec/classes/nginx_spec.rb
- templates/conf.d/nginx.conf.erb
Following on work from previous PRs to add stream log changes to the module.
Updated changes to fix file conflicts and newer changes in v4.1.0
The configuration in Hiera:
```yaml
nginx::stream_access_log: '/var/log/nginx/nginx-stream-access.log'
nginx::stream_custom_format_log: 'basic'
nginx::stream_log_format:
basic: '$remote_addr [$time_local] $protocol $status $bytes_sent $bytes_received $session_time $server_addr:$server_port $upstream_addr'
```
Adds the following lines to nginx.conf:
```shell
+  log_format basic '$remote_addr [$time_local] $protocol $status $bytes_sent $bytes_received $session_time $server_addr:$server_port $upstream_addr';
+  access_log /var/log/nginx/nginx-stream-access.log basic;
```
If `stream_custom_format_log` is not set, nginx will use the built-in `combined` …
> Add stream log support

- manifests/package/debian.pp
Without this setting, we tell apt to download release information for all architectures apt knows. This includes i386 on amd64 systems. nginx doesn't publish i386 packages. because of that, it results in a warning during apt update:
N: Skipping acquire of configured file 'nginx/binary-i386/Packages' as repository 'https://nginx.org/packages/ubuntu jammy InRelease' doesn't support architecture 'i386'
This is fixed with this change.
> apt::source: configure repo only for current architecture

- REFERENCE.md
- manifests/config.pp
- manifests/init.pp
- spec/classes/nginx_spec.rb
- templates/conf.d/nginx.conf.erb
Allow specification of up to three-level subdirectory hierarchy for both [client_body_temp_path](https://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_temp_path) and [proxy_temp_path](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_temp_path) options
This allows for the existing string option to specify just the path as it works now, and for an alternate type as an array with the first element as the path, and the up to 3 additional integers for each level
- Updated docs
- Updated tests
> Enable subdirectory hierarchy for client_body and proxy temp paths

- REFERENCE.md
- manifests/resource/location.pp
- manifests/resource/server.pp
- spec/defines/resource_location_spec.rb
- templates/server/locations/proxy.erb
This adds support for the proxy_cache_convert_head directive:
https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_convert_head
> Add support for proxy_cache_convert_head

- templates/server/fastcgi.conf.erb
- templates/server/uwsgi_params.erb
Puppet 8 will default to not sending legacy facts.  Start replacing those with the one that supersede them.
There might be more, but with this change i have no difference on my nodes when running with `--no-include_legacy_facts`.
> Fix legacy facts usage

- manifests/package/redhat.pp
- manifests/params.pp
- metadata.json
- spec/acceptance/class_spec.rb
> Add EL 8/9 to supported OS

- spec/defines/resource_server_spec.rb
- templates/server/server_header.erb
- templates/server/server_ssl_header.erb
Add access_log and error_log to rewrite sections.
Fixes #1545
> Add access and error logs directives when `www_to_non_www` or `non_www_to_www` is used

- metadata.json
Drop EoL Ubuntu 18.04 from `metadata.json`.
> metadata.json: drop EoL Ubuntu 18.04

- REFERENCE.md
- manifests/init.pp
- types/package_source.pp
This is not a free-form String so prefer an enum and add some
documentation about the supported values.
> Improve `nginx::package_source` documentation

- REFERENCE.md
- manifests/init.pp
- spec/classes/nginx_spec.rb
- templates/conf.d/nginx.conf.erb
- templates/streamhost/streamhost.erb
According to the official NGINX documentation the parameter gzip_proxied allows multiple parameters.
Closes #1567
> Allow multiple values in `gzip_proxied` parameter

- spec/defines/resource_server_spec.rb
- templates/server/server_ssl_header.erb
- templates/server/server_ssl_ipv6_listen.erb
- templates/server/server_ssl_settings.erb
This PR is meant to create the http2 directive: http://nginx.org/en/docs/http/ngx_http_v2_module.html#http2
Fixes following warning in nginx:
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead.
> Add `http2` directive instead of `listen` option

- REFERENCE.md
- manifests/resource/location.pp
- spec/defines/resource_location_spec.rb
- templates/server/location_header.erb
Adds support for multiple `limit_req` statements in a `location` by allowing `limit_zone` to be passed as an array OR a string.
Fixes #1569
> Add support for multiple `limit_req` statements in `location` directives

- REFERENCE.md
- metadata.json
- spec/acceptance/class_spec.rb
- spec/acceptance/nginx_server_spec.rb
- spec/classes/nginx_spec.rb
there is already breaking changes on master, so next releease will be major
test have been broken for a while and will be fixed in https://github.com/voxpupuli/puppet-nginx/pull/1596
> drop support for Debian 10

- REFERENCE.md
- manifests/init.pp
- manifests/resource/mailhost.pp
- spec/acceptance/nginx_mail_spec.rb
- spec/classes/nginx_spec.rb
- spec/defines/resource_mailhost_spec.rb
- spec/defines/resource_server_spec.rb
- templates/mailhost/mailhost_common.epp
this fixes the acceptance tests. But there is a bigger issue here. The code in manifests/init.pp is not idempotent:
```puppet
String[1] $nginx_version                                = pick(fact('nginx_version'), '1.6.0'),
```
Turns out on the first run the fact might not be set yet leading to a pre 1.15.0 compatible configuration on systems wich ship a newer version of nginx. Leading to
```
nginx: [emerg] unknown directive "ssl" in /etc/nginx/sites-enabled/www.puppetlabs.com.conf:25
```
> raise default version to 1.16.0

- REFERENCE.md
- manifests/resource/server.pp
- spec/defines/resource_server_spec.rb
- templates/server/server_header.erb
- templates/server/server_ssl_header.erb
> Allow specifying error_log severity for servers

- .github/CONTRIBUTING.md
- .github/labeler.yml
- .github/workflows/ci.yml
- .msync.yml
- Gemfile
> modulesync 9.0.0

- REFERENCE.md
- manifests/init.pp
This PR remove backwards-compatible data types which where bogus.
It is intended to be rebased on top of master and merged when we want to cut a new major version and people had the time to update their code to not rely on these.
> Remove legacy data types

- README.md
- lib/facter/nginx_version.rb
- manifests/params.pp
- spec/classes/nginx_spec.rb
Replace legacy facts to improve compatibility with Puppet 8.
N/A
> Fix use of legacy facts

- spec/defines/resource_map_spec.rb
- templates/conf.d/map.epp
When passing some `include_files` but no `mappings`, catalog compilation fail with the following error message:
```
Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Method call, max(): Wrong number of arguments need at least one (file: /etc/puppetlabs/code/environments/romain/modules/nginx/templates/conf.d/map.epp, line: 26, column: 48)
```
Refactoring done in #1575 has introduced this regression.
> Fix usage of `include_files` in `nginx::resource::map`

- REFERENCE.md
- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- manifests/resource/mailhost.pp
- spec/acceptance/nginx_mail_spec.rb
- spec/classes/nginx_spec.rb
- spec/defines/resource_mailhost_spec.rb
- templates/conf.d/nginx.conf.erb
- templates/mailhost/mailhost_ssl.epp
While redhat installs the mail packages by default, arch doesn't and therefore you need to be able to define that package for installation.
> Disable mail relay in nginx 1.14

- manifests/resource/location.pp
- spec/defines/resource_location_spec.rb
- templates/server/location_header.erb
Hello,
This PR adds the support of the following directives at location level
- access_log
- error_log
- log_not_found 
it allows to be more precise in the logging strategy. 
Hope it helps.
> add support to access_log, error_log log_not_found per location

- spec/defines/resource_location_spec.rb
- templates/server/location_header.erb
In version 7.0.0 [log statements functionality added per location](https://github.com/voxpupuli/puppet-nginx/pull/1471/files).
But with it there are some problems:
1. Intendations. Log statements intendation is 2 space from the left (top level intendation)
2. Wrong default behavieour. When error_log is undef, statement still creates.
See screenshot
> Fix logging statements in locations

- REFERENCE.md
- manifests/resource/server.pp
- templates/server/server_ssl_settings.erb
Fixes a problem introduced with #1645. The global default for `ssl_verify_client` is `on`, which means that it will be switched on for anyone who uses `ssl_trusted_certificates` for OCSP purposes, for example.
This commit changes the global default to `unset`. This will require people to be explicit if they want `ssl_verify_client`.
The `server_ssl_settings.erb` template now sets `ssl_verify_client` explicitly to 'on' if `ssl_client_certificate` is set AND `ssl_verify_client` is unset. This keeps the current behaviour for what I think is the majority of cases.
Tested to the best of my ability, and I could not find any other cases that expect a value to be present for `ssl_verify_client`.
Fixes #1646
> Fix ssl verify client compat

- spec/defines/resource_mailhost_spec.rb
- templates/mailhost/mailhost_ssl.epp
This change ensures that the `ssl` parameter is also applied to the IPv6 listen directive ([::]:993) when the Nginx version is ≥ 1.15.0. Previously, only the IPv4 directive (*:993 ssl) included the ssl parameter.
> Add ssl parameter to IPv6 listen directive
