- README.markdown
> README: fix hiera nginx_locations example

- manifests/resource/vhost.pp
- templates/vhost/vhost_header.erb
- templates/vhost/vhost_ssl_header.erb
This adds a parameter to easily set a vhost in maintenance mode.
> feat: add an easy maintenance page support

- manifests/config.pp
- spec/classes/config_spec.rb
> config: refined worker_processes validation

- manifests/init.pp
> init: fix create_resources declarations for old puppet versions

- templates/vhost/vhost_header.erb
- templates/vhost/vhost_ssl_header.erb
> vhost: simplify maintenance variable code

- manifests/config.pp
- manifests/resource/vhost.pp
- spec/defines/resource_vhost_spec.rb
- templates/vhost/vhost_ssl_header.erb
Hey @jfryman, I added some things to support the new http2 protocol addition that has been done in nginx 1.9.5 (https://www.nginx.com/blog/nginx-1-9-5/).
If there's things wrong/missing to merge this, let me know.
> Http2 support

- manifests/config.pp
This parameter has no effect as of #642
> Deprecate $proxy_conf_template

- templates/vhost/location_header.erb
- templates/vhost/locations/proxy.erb
- templates/vhost/vhost_header.erb
- templates/vhost/vhost_ssl_header.erb
- templates/vhost/vhost_ssl_settings.erb
This is what I was able to correct this far based on the vhosts I've been creating.
> Remove extra white space

- README.markdown
Add an example for a simple reverse proxy to the README.
Fixes #751
> Issue 751 Add an example for a simple reverse proxy to the README

- manifests/resource/vhost.pp
maybe also should add, a note about the server_name should be '_'
see nginx official doc http://nginx.org/en/docs/http/ngx_http_core_module.html#listen
> update catch all vhost example doc

- manifests/resource/location.pp
- manifests/resource/vhost.pp
- spec/defines/resource_location_spec.rb
- templates/vhost/location_header.erb
Add "satisfy" option to the location section 
https://www.nginx.com/resources/admin-guide/restricting-access/
http://nginx.org/en/docs/http/ngx_http_core_module.html?&_ga=1.238118336.1949645469.1456390584#satisfy
> Add "satisfy" option to the location section

- templates/vhost/location_header.erb
> Fix location template to not add empty line

- spec/unit/nginx_version_spec.rb
> add test for #813

- manifests/params.pp
> fixing issue #837

- manifests/package/debian.pp
Sorry... Introduced a wrong order with the fix/PR yesterday.
> Merge Request #851 introduced a wrong order of installation

- manifests/resource/location.pp
- manifests/resource/vhost.pp
- spec/defines/resource_location_spec.rb
- templates/vhost/locations/uwsgi.erb
http://nginx.org/en/docs/http/ngx_http_uwsgi_module.html#uwsgi_read_timeout
> Expose the uwsgi_read_timeout parameter

- .fixtures.yml
> migrate fixtures to github links

- lib/facter/nginx_version.rb
Reverts voxpupuli/puppet-nginx#908
> Revert "Prevent custom fact from complaining when openresty is installed"

- templates/vhost/locations/fastcgi.erb
> Move try_files

- .msync.yml
- .rubocop.yml
- .sync.yml
- Gemfile
- Rakefile
- spec/spec_helper.rb
> Update based on voxpupuli/modulesync_config 0.13.4

- manifests/resource/vhost.pp
- spec/defines/resource_vhost_spec.rb
- templates/vhost/vhost_footer.erb
Forgot to allow supporting passenger_pre_start to be an array in #880
> Support array as well as string for passenger_pre_start

- manifests/package/redhat.pp
- spec/classes/package_spec.rb
This fixes a minor failure in the acceptance tests, though may still have to rework slightly for #938
> add before => Package['nginx'] on repo absent ensures

- spec/defines/resource_location_spec.rb
- spec/defines/resource_vhost_spec.rb
> fix rubocop failures after rubocop version update

- README.md
- docs/hiera.md
Suggested docs changes that reflect a bit better the work we've been doing and will be doing
> docs changes to reflect upcoming changes

- manifests/resource/location.pp
- spec/defines/resource_location_spec.rb
- templates/vhost/locations/alias.erb
- templates/vhost/locations/directory.erb
This is _not_ the fix I had been hoping to submit, reworking the location templates logic a bit more dramatically, but this resolves a problem I'm seeing, and I think should not introduce any new problems.
> allow try_files and index in location resource

- spec/defines/resource_upstream_spec.rb
- templates/upstream/upstream_footer.erb
- templates/upstream/upstream_header.erb
There were a few ways to do this; this one isn't great, but seems to work.
Thoughts about the indenting / formatting changes?
> Put keepalive at bottom of upstream_cfg_{append,prepend} sections (#641)

- manifests/resource/location.pp
- templates/vhost/location_footer.erb
This PR addresses https://github.com/voxpupuli/puppet-nginx/issues/964
> Document include param for location and fix whitespace issue (issue #976)

- manifests/resource/location.pp
- manifests/resource/server.pp
- spec/defines/resource_location_spec.rb
- spec/defines/resource_server_spec.rb
- templates/server/location_header.erb
- templates/server/server_header.erb
- templates/server/server_ssl_header.erb
> Added auth_request configuration capability

- .msync.yml
- .rubocop.yml
- .travis.yml
- Gemfile
- spec/acceptance/nodesets/fedora-24-x64.yml
- spec/acceptance/nodesets/fedora-25-x64.yml
- spec/default_facts.yml
- spec/unit/facter/util/fact_nginx_version_spec.rb
> modulesync 0.16.7

- CHANGELOG.md
- metadata.json
> release 0.6.0

- .gitignore
- .msync.yml
- .travis.yml
- Gemfile
- Rakefile
- metadata.json
- spec/spec_helper.rb
> modulesync 0.19.0

- README.md
Add streamhost example to README from @jurim76 (#1019)
> docs fix from @jurim76

- manifests/init.pp
> change names_hash_bucket_size default string->int

- manifests/init.pp
> change proxy_headers_hash_bucket_size default string->int

- manifests/init.pp
> change worker_connections default string->int

- manifests/init.pp
> change names_hash_max_size default string->int

- manifests/init.pp
> change proxy_use_temp_path default false->undef

- manifests/init.pp
> change proxy_cache_path default false->undef

- manifests/init.pp
> change http_cfg_append default false->undef

- manifests/init.pp
> change fastcgi_cache_use_stale default false->undef

- manifests/init.pp
> change events_use default false->undef

- manifests/init.pp
> change fastcgi_cache_path default false->undef

- manifests/init.pp
> change http_cfg_prepend default false->undef

- manifests/init.pp
> change fastcgi_cache_key default false->undef

- manifests/resource/mailhost.pp
- spec/defines/resource_mailhost_spec.rb
> replace validate_* with datatypes

- manifests/resource/server.pp
- spec/defines/resource_server_spec.rb
> replace validate_* calles with datatypes in server.pp

- manifests/resource/server.pp
- spec/defines/resource_server_spec.rb
Reverts voxpupuli/puppet-nginx#1062 - will redo with proper commit history
> Revert "Add fastcgi index"

- manifests/resource/server.pp
- spec/defines/resource_server_spec.rb
> Adding FastCGI index

- .fixtures.yml
- manifests/resource/mailhost.pp
- spec/classes/nginx_spec.rb
- spec/default_module_facts.yml
- spec/defines/resource_geo_spec.rb
- spec/defines/resource_location_spec.rb
- spec/defines/resource_mailhost_spec.rb
- spec/defines/resource_map_spec.rb
- spec/defines/resource_server_spec.rb
- spec/defines/resource_stream_spec.rb
- spec/defines/resource_upstream_spec.rb
The build was broken due to one of our dependencies, (puppetlabs/apt),
starting to use the puppet 4 $facts hash.
> Use rspec-puppet-facts

- docs/quickstart.md
My big contribution for the year :)
> Fix misspelling

- manifests/params.pp
- metadata.json
> Add DragonFly BSD support

- CHANGELOG.md
- metadata.json
> Release 0.7.1

- manifests/resource/server.pp
- templates/server/server_header.erb
- templates/server/server_ipv6_listen.erb
- templates/server/server_ssl_header.erb
- templates/server/server_ssl_ipv6_listen.erb
Centralizes template logic and reduces requirement on ipaddres6 fact presence.
> Improve logic for ipv6 listening

- CHANGELOG.md
- metadata.json
> release 0.8.0

- .msync.yml
- .travis.yml
- Gemfile
> modulesync 1.4.1

- CHANGELOG.md
- metadata.json
> release 0.9.0

- manifests/resource/map.pp
> replace validate_* with datatypes in resource::map

- CHANGELOG.md
- metadata.json
> release 0.10.0

- manifests/params.pp
> use correct nginx package name on archlinux

- manifests/package.pp
- manifests/package/debian.pp
- manifests/package/redhat.pp
- manifests/params.pp
- manifests/resource/streamhost.pp
- manifests/resource/upstream/member.pp
- manifests/service.pp
> switch from topscope facts to facts hash

- CHANGELOG.md
- metadata.json
> release 0.11.0

- spec/spec_helper_acceptance.rb
Align the spec_helper_acceptance with the ones in our other repos (todo: manage it via modulesync...)
> cleanup spec_helper_acceptance

- spec/acceptance/init_spec.rb
> add acceptance test to verify default values

- .github/CONTRIBUTING.md
- .msync.yml
- Gemfile
> modulesync 1.9.0-12-gacb0134

- spec/classes/nginx_spec.rb
> increase spec test coverage

- HISTORY.md
- metadata.json
> release 0.12.0

- README.md
Please remove my name and email from the README. I haven't been active for a long time and don't plan to in future.
I could commit directly (I'm a member of `@voxpupuli/collaborators`, though will be leaving the team) but just want this on record in case anyone finds the commit strange.
EDIT: Have left `@voxpupuli`
> README: Remove old email address

- .msync.yml
- .travis.yml
- Gemfile
- metadata.json
- spec/spec_helper_acceptance.rb
> modulesync 1.9.6

- manifests/params.pp
> add default values for AIX servers

- manifests/package/redhat.pp
- spec/classes/nginx_spec.rb
Updated gpgkey with new location as detailed by phusion https://twitter.com/phusion_nl/status/1062323305225641984
n/a
> update location of passenger repo gpgkey

- Gemfile
> pin parallel_tests for ruby 2.1.0

- .travis/setup.sh
> simplify travis helper

- CHANGELOG.md
> release 0.16.0

- .msync.yml
- .sync.yml
- .travis.yml
> modulesync 2.7.0 and drop puppet 4

- metadata.json
> Allow puppetlabs/concat 6.x

- .github/CONTRIBUTING.md
- .msync.yml
- .travis.yml
- Dockerfile
- Gemfile
- Rakefile
- manifests/params.pp
- manifests/resource/mailhost.pp
- manifests/resource/streamhost.pp
- spec/spec_helper.rb
> modulesync 2.9.0

- manifests/package/redhat.pp
- manifests/params.pp
- metadata.json
- spec/classes/nginx_spec.rb
> Add VirtuozzoLinux support

- .travis/setup.sh
> delete legacy travis directory

- README.md
> Fix syntax error in the complex proxy example

- README.md
this type of link doesn't seem to work
> fix quickstart link

- spec/defines/resource_location_spec.rb
fix rubocop offenses introduced with #1420
> fix rubocop offenses introduced with #1420

- manifests/resource/server.pp
> fix comment

- manifests/config.pp
- manifests/init.pp
- spec/classes/nginx_spec.rb
- templates/conf.d/nginx.conf.erb
Adds a parameter to enable or disable pcre_jit
None
> add parameter for pcre_jit

- manifests/config.pp
- manifests/init.pp
- manifests/resource/location.pp
- manifests/resource/server.pp
- spec/classes/nginx_spec.rb
- spec/defines/resource_location_spec.rb
- spec/defines/resource_server_spec.rb
- templates/conf.d/nginx.conf.erb
- templates/server/location_header.erb
- templates/server/server_header.erb
Add reset_timedout_connection parameter
Fixes #1447
> add reset_timedout_connection parameter

- .github/CONTRIBUTING.md
- .github/workflows/ci.yml
- .msync.yml
- Dockerfile
- Gemfile
- spec/defines/resource_server_spec.rb
> modulesync 4.1.0

- CHANGELOG.md
- REFERENCE.md
- metadata.json
> Release 3.2.0

- CHANGELOG.md
- REFERENCE.md
- metadata.json
> Release 3.2.1

- manifests/params.pp
Releated info: https://github.com/voxpupuli/beaker-hostgenerator/pull/244
> Switch away from os.distro.codename fact

- templates/server/location_header.erb
make `allow/deny` lists unique
> remove allow/deny lists duplicates

- CHANGELOG.md
- REFERENCE.md
- metadata.json
If there is any other breaking change pending I can hold it, let me know
Closes #1495
> Release 4.0.0

- .msync.yml
- .rubocop.yml
- Gemfile
- Rakefile
- spec/spec_helper.rb
> modulesync 5.3.0

- REFERENCE.md
- manifests/init.pp
- types/gzipproxied.pp
> Add custom type for gzip_proxied

- CHANGELOG.md
- REFERENCE.md
- metadata.json
> Release 4.2.0

- manifests/config.pp
- manifests/init.pp
- spec/classes/nginx_spec.rb
- templates/conf.d/nginx.conf.erb
This PR allows setting of map_hash_bucket parameters
> allow setting of map_hash_bucket_size and map_hash_max_size

- CHANGELOG.md
- REFERENCE.md
- manifests/resource/map.pp
- manifests/resource/server.pp
- manifests/resource/streamhost.pp
- manifests/resource/upstream.pp
- metadata.json
> Release 4.3.0

- CHANGELOG.md
- metadata.json
> Release 4.4.0

- .fixtures.yml
- manifests/config.pp
- manifests/params.pp
- manifests/resource/upstream.pp
- metadata.json
> puppetlabs/stdlib: Allow 9.x & puppetlabs/concat: Allow 8.x & 9.x

- .github/CONTRIBUTING.md
- .github/workflows/ci.yml
- .sync.yml
> modulesync 6.1.0
